### PR TITLE
Fixs and Improvements for EndermanEscapeEvent

### LINKED ISSUE #12500: Cancelling EndermanEscapeEvent can't bypass damage avoidance
### Expected behavior

it takes damage

### Observed/Actual behavior

not taking damage

### Steps/models to reproduce

```java
@EventHandler
public void onEndermanHit(EndermanEscapeEvent event){
    event.setCancelled(true);
}
```
shoot an arrow to the enderman, it won't teleport away, but also won't take damage

### Plugin and Datapack List

Just a test plugin with the code above

### Paper version

This server is running Paper version 1.21.4-225-main@0767902 (2025-04-11T21:49:39Z) (Implementing API version 1.21.4-R0.1-SNAPSHOT)
You are 2 version(s) behind
Download the new version at: https://papermc.io/downloads/paper
Previous version: 1.21.4-211-6ea4202 (MC: 1.21.4)

### Other

_No response_

### PR DESCRIPTION
**Pull request by Doc94**
Related to fix https://github.com/PaperMC/Paper/issues/12500 this PR handle two things.

- Improvement docs for mention the vanilla behaviour for arrows where the damage are not apply in any case
- Add support for two reasons ignored by damage not related to projectiles like rain

### CODE REVIEW

File: paper-api/src/main/java/com/destroystokyo/paper/event/entity/EndermanEscapeEvent.java [hunk 1]
```diff
@@ -42,7 +44,8 @@ public boolean isCancelled() {
      * Cancels the escape.
      * <p>
      * If this escape normally had resulted in damage avoidance such as indirect,
-     * the enderman will now take damage.
+     * the enderman will now take damage. However, this does not change the Enderman's
+     * innate immunities or damage behavior like arrows where the damage never happen.
```
Comment (Toffikk) [inline paper-api/src/main/java/com/destroystokyo/paper/event/entity/EndermanEscapeEvent.java]: `happen` -> `happens`

**Review by Owen1212055 — APPROVED** [review]

**Review by lynxplay — APPROVED** [review]
I do want to note that the CRITICAL_HIT thing is obviously completely misleading in what it actually represents, but fixing that is outside of the PR scope.

**Comment by Doc94** [comment]
> I do want to note that the CRITICAL_HIT thing is obviously completely misleading in what it actually represents, but fixing that is outside of the PR scope.

Yeah.. for future reference maybe can be just a "other" because not sure in what case now can throw
