### PR TITLE
Separate tick count to ensure vanilla parity

### LINKED ISSUE #12075: The Wither's mob AI behavior is inconsistent with the vanilla Minecraft.
### Expected behavior

In vanilla,the Wither does not lose its hostility towards Iron Golems when the chunk unloads.

### Observed/Actual behavior

In Paper,after unloading and reloading a chunk,the Wither momentarily loses its hostility,causing it to escape the Wither cage.

### Steps/models to reproduce

Construct the relevant mechanism within a chunk.
Move away from the chunk to ensure it unloads
Return to reload the chunk and observe the Wither's behavior.

Image

### Plugin and Datapack List

Issue persists in a clean Paper instance without plugins or datapacks.
This issue is unrelated to plugins or datapacks.

### Paper version

All Paper version.

### Other

_No response_

### PR DESCRIPTION
**Pull request by HaHaWTH**
Closes #12075.

This pull request introduces another entity tick counter `totalTickCount` for api usage, reset vanilla `tickCount` instead of restoring value from Spigot's `Spigot.ticksLived` tag to keep vanilla parity.

## Analysis

Spigot's restore tickCount behavior([See original patch](https://hub.spigotmc.org/stash/projects/SPIGOT/repos/spigot/browse/CraftBukkit-Patches/0027-Save-ticks-lived-to-nbttag.patch)) causes potential issues with Wither's ai, see code below, and lead to wither loses its target when entities are reloaded:
image

## Api Changes

Now `Entity#getTicksLived` gets value from totalTickCount to avoid api behavior breakage, `Entity#setTicksLived` sets both `tickCount` and `totalTickCount`.

Currently the totalTickCount is only used for apis, if the breakage is fine, the extra counter can be removed.

### CODE REVIEW

**Review by lynxplay — APPROVED** [review]

File: paper-server/patches/sources/net/minecraft/world/entity/Entity.java.patch [hunk 1]
```diff
@@ -1,5 +1,13 @@
 --- a/net/minecraft/world/entity/Entity.java
 +++ b/net/minecraft/world/entity/Entity.java
+@@ -3,7 +_,6 @@
+ import com.google.common.collect.ImmutableList;
+ import com.google.common.collect.Iterables;
+ import com.google.common.collect.Lists;
+-import com.google.common.collect.Sets;
+ import com.google.common.collect.ImmutableList.Builder;
+ import com.mojang.logging.LogUtils;
+ import it.unimi.dsi.fastutil.floats.FloatArraySet;
```
Comment (NoahvdAa) [inline paper-server/patches/sources/net/minecraft/world/entity/Entity.java.patch]: (can be handled by merger) unnecessary diff noise?

**Review by NoahvdAa — APPROVED** [review]

File: paper-server/patches/sources/net/minecraft/world/entity/Entity.java.patch [hunk 2]
```diff
@@ -860,7 +861,7 @@
 +            // CraftBukkit start
 +            // Spigot start
 +            if (this instanceof net.minecraft.world.entity.LivingEntity) {
-+                this.tickCount = compound.getInt("Spigot.ticksLived");
++                this.totalEntityAge = compound.getInt("Spigot.ticksLived"); // Paper
```
Comment (Warriorrrr) [inline paper-server/patches/sources/net/minecraft/world/entity/Entity.java.patch:864]: Kinda unrelated to this PR but, is there still a reason to only read this if the entity is a living entity?

**Review by Warriorrrr — COMMENTED** [review]
In the despawn time check inside Entity#tick, totalEntityAge should also be used instead if we don't want unloading to affect their configured despawn time.

File: paper-server/patches/sources/net/minecraft/world/entity/Entity.java.patch (hunk 2 above)
Comment (HaHaWTH) [reply paper-server/patches/sources/net/minecraft/world/entity/Entity.java.patch:864]: Entity despawn now uses the `totalEntityAge`

Comment (HaHaWTH) [reply paper-server/patches/sources/net/minecraft/world/entity/Entity.java.patch:864]: > Kinda unrelated to this PR but, is there still a reason to only read this if the entity is a living entity?

Spigot api resets tickCount for non-living entities, so leaving it here just for api behavior is same as spigot.

**Review by Owen1212055 — APPROVED** [review]

**Review by Dreeam-qwq — APPROVED** [review]

**Review by Machine-Maker — APPROVED** [review]
