### PR TITLE
Fix the cause of Phantom generation

### LINKED ISSUE #12978: Phantom SpawnReason typo
### Expected behavior

Phantoms should spawn with `SpawnReason.NATURAL` as they are naturally spawning hostile mobs, not patrol mobs like pillagers. This is the expected behavior for consistency with other naturally spawning mobs and proper API semantics.

### Observed/Actual behavior

Since the 1.21.5 patch, phantoms are spawning with `SpawnReason.PATROL` instead of the correct `SpawnReason.NATURAL`. This breaks plugin logic that depends on the proper spawn reason classification, causing phantoms to be incorrectly categorized as patrol mobs rather than natural spawns.

### Steps/models to reproduce

1. Create a plugin that listens to the `CreatureSpawnEvent`
2. Check the spawn reason when a phantom spawns
3. Set up conditions for phantom spawning (player not sleeping for 3+ days)
4. Observe that the event reports `SpawnReason.PATROL` instead of `SpawnReason.NATURAL`

Alternatively, use this minimal test listener:
```java
@EventHandler
public void onCreatureSpawn(CreatureSpawnEvent event) {
    if (event.getEntityType() == EntityType.PHANTOM) {
        Bukkit.getLogger().info("Phantom spawned with reason: " + event.getSpawnReason());
    }
}
```

### Plugin and Datapack List

This issue occurs with any plugin setup. For testing purposes, a minimal plugin with the CreatureSpawnEvent listener is sufficient. No specific plugins or datapacks are required to reproduce this bug.

**Test Environment:**
- No additional plugins required
- No datapacks required
- Vanilla Paper server is sufficient to reproduce

### Paper version

1.21.8-31

### Other

_No response_

### PR DESCRIPTION
**Pull request by Swim5678**
fix #12978

### CODE REVIEW

**Comment by Swim5678** [comment]
The cause of Phantom generation was incorrectly labeled as PATROL, but it should actually be NATURAL

**Review by NoahvdAa — APPROVED** [review]
Congrats on making your first PR, welcome to Paper :)

**Comment by Swim5678** [comment]
> Congrats on making your first PR, welcome to Paper :)

Thank you❤️

File: paper-server/patches/sources/net/minecraft/world/level/levelgen/PhantomSpawner.java.patch [hunk 1]
```diff
@@ -46,7 +46,7 @@
                                                              level, currentDifficultyAt, EntitySpawnReason.NATURAL, spawnGroupData
                                                          );
 -                                                        level.addFreshEntityWithPassengers(phantom);
-+                                                        level.addFreshEntityWithPassengers(phantom, org.bukkit.event.entity.CreatureSpawnEvent.SpawnReason.PATROL); // CraftBukkit
```
Comment (dawon) [inline paper-server/patches/sources/net/minecraft/world/level/levelgen/PhantomSpawner.java.patch:49]: Shouldn't a `// Paper` comment be here? Or the CraftBukkit one is enough?

Comment (Swim5678) [reply paper-server/patches/sources/net/minecraft/world/level/levelgen/PhantomSpawner.java.patch:49]: `// CraftBukkit` was not written by me, it was written by kennytv.

**Review by electronicboy — APPROVED** [review]
