### PR TITLE
Use target level for waypoint modify command

### LINKED ISSUE #12931: Invisible Armor Stand does still show in the LocatorBar
### Expected behavior

No waypoint in the overworld after modifying a waypoint in the nether

### Observed/Actual behavior

A waypoint tracked by the locator bar that points to a new "ghost" entity in the overworld, at the coordinates of the position in the nether of the modified entity

### Steps/models to reproduce

1. Spawn an ArmorStand in the nether
2. Modify it using `Bukkit.dispatchCommand("waypoint modify %s color gold %s", entity.uniqueId.toString())`
3. New waypoint in the overworld exists that points to coordinates that belong to the nether (without any entity visible)

### Plugin and Datapack List

[01:30:55 INFO]: ? Server Plugins (4):
[01:30:55 INFO]: Bukkit Plugins:
[01:30:55 INFO]:  - CommandAPI, eventrox, fakeplayer, TAB

eventrox is my own plugin that just spawns the armorstand, gets its uuid and calls the command on the entity.

### Paper version

This server is running Paper version 1.21.8-25-main@846c64f (2025-08-04T13:12:55Z) (Implementing API version 1.21.8-R0.1-SNAPSHOT)
You are running the latest version

### Other

 Issue looks similar to this PR: https://github.com/PaperMC/Paper/pull/12715

```kotlin 

        val location = player.location
        val entity =
            location.world.spawn(entityLocation, ArmorStand::class.java, CreatureSpawnEvent.SpawnReason.CUSTOM) {
                it.isVisible = false
                it.setGravity(false)
                it.isInvulnerable = true
                it.isSilent = true
            }

        val transmitRange = entity.getAttribute(Attribute.WAYPOINT_TRANSMIT_RANGE)
        transmitRange?.baseValue = 6e7

        val entitySelector: String? = entity.uniqueId.toString()
        
        val colorCmd = String.format("waypoint modify %s color gold", entitySelector)
        val styleCmd = String.format("waypoint modify %s style set eventrox:waypoint", entitySelector)

        Bukkit.dispatchCommand(Bukkit.getConsoleSender(), colorCmd)
        Bukkit.dispatchCommand(Bukkit.getConsoleSender(), styleCmd)
```

This is my code that creates a waypoint in the overworld when the player runs a command that should spawn the armorstand in the nether. Without the style/color commands, there are no waypoints in the overworld. This does also not happen if the player itself is set as the CommandSender. Using the console of the server also did not let me reproduce the behaviour of my plugin.

### PR DESCRIPTION
**Pull request by Doc94**
Fixes https://github.com/PaperMC/Paper/issues/12931
Currently the `waypoint modify` use the level of the command executer for save changes, if the target is in another dimension the command ignore that and send the modify to the executer world adding a waypoint and keeping... in vanilla singleplayer when join again to the world the waypoint its removed

PS: I dont find a MOJIRA issue for this...

### CODE REVIEW

File: paper-server/patches/sources/net/minecraft/server/commands/WaypointCommand.java.patch [hunk 1]
```diff
@@ -0,0 +1,11 @@
+--- a/net/minecraft/server/commands/WaypointCommand.java
++++ b/net/minecraft/server/commands/WaypointCommand.java
+@@ -165,7 +_,7 @@
+     }
+ 
+     private static void mutateIcon(CommandSourceStack source, WaypointTransmitter waypoint, Consumer<Waypoint.Icon> mutator) {
+-        ServerLevel level = source.getLevel();
++        ServerLevel level = (waypoint instanceof LivingEntity livingEntity) ? (net.minecraft.server.level.ServerLevel) livingEntity.level() : source.getLevel(); // Paper - use level of waypoint if it's a living entity for broadcast
```
Comment (Doc94) [inline paper-server/patches/sources/net/minecraft/server/commands/WaypointCommand.java.patch]: this is based in the list argument where the same check is make for the waypoints, not sure in what case the waypoint cannot be a LivingEntity

**Review by lynxplay — APPROVED** [review]

**Comment by Owen1212055** [comment]
Please make a mojang report and then link it as a comment

**Comment by Doc94** [comment]
> Please make a mojang report and then link it as a comment

Ready https://mojira.dev/MC-300685

**Review by Machine-Maker — APPROVED** [review]
