### PR TITLE
Fix #12721

### LINKED ISSUE #12721: Cancelling HangingPlaceEvent causes an existing LeashFenceKnot to break when leashing more mobs to it
### Expected behavior

Either cancelling the event to leave the `LeashFenceKnot` intact, or for `HangingPlaceEvent` to not be fired at all as no new entity is being created.

### Observed/Actual behavior

If a player attempts to leash additional mobs to an already existing `LeashFenceKnot`, a `HangingPlaceEvent` gets fired. This already seems strange to me as there is no new entity being created. If this event is then cancelled (e.g a protection plugin like GriefPrevention), the `LeashFenceKnot` is removed and all entities are unleashed.

### Steps/models to reproduce

1. Leash one or more mobs to a fence 
2. Create and load a plugin which cancels `HangingPlaceEvent`
3. Attempt to leash further mobs to the fence
4. Observe how all mobs are unleashed when the event is cancelled

### Plugin and Datapack List

Issue is reproducible with any plugin that cancels `HangingPlaceEvent`. No additonal plugins or datapacks required.

### Paper version

This server is running Paper version 1.21.6-28-main@803baf0 (2025-06-22T17:49:49Z) (Implementing API version 1.21.6-R0.1-SNAPSHOT)
You are running the latest version
Previous version: 1.21.4-232-12d8fe0 (MC: 1.21.4)

### Other

_No response_

### PR DESCRIPTION
**Pull request by Owen1212055**
Track when knots are created and only fire the event then

### CODE REVIEW

File: paper-server/patches/sources/net/minecraft/world/entity/decoration/LeashFenceKnotEntity.java.patch [hunk 1]
```diff
@@ -27,3 +27,24 @@
...
  
+@@ -120,7 +_,12 @@
+         return this.level().getBlockState(this.pos).is(BlockTags.FENCES);
+     }
+ 
++    // Paper start - Track if a knot was created
+     public static LeashFenceKnotEntity getOrCreateKnot(Level level, BlockPos pos) {
++        return getOrCreateKnot(level, pos, null);
++    }
++    public static LeashFenceKnotEntity getOrCreateKnot(Level level, BlockPos pos, @Nullable java.util.concurrent.atomic.AtomicBoolean created) {
```
Comment (kennytv) [inline paper-server/patches/sources/net/minecraft/world/entity/decoration/LeashFenceKnotEntity.java.patch]: you can use MutableBoolean from somewhere

**Review by kennytv — APPROVED** [review]
