### PR TITLE
Fix BlockRedstoneEvent for tripwire hooks

### LINKED ISSUE #9714: Tripwire hook not registering properly on BlockRedstoneEvents
### Expected behavior

Whenever an entity goes onto a wire connecting two tripwire hooks, there should fire two induvidual BlockRedstoneEvents for the two related tripwire hooks.

For example, when an entity goes onto a tripwire with one end having a tripwire hook facing east, and the other end a tripwire hook facing west, then there should trigger a BlockRedstoneEvent once for both of the tripwire hooks.

### Observed/Actual behavior

Only east facing and north facing tripwire hooks show up in BlockRedstoneEvent. The Event also triggers at least 2 times to the maximum tested value of 3 times (depending on the length of the wire) for the same tripwire hook.

### Steps/models to reproduce

Make a plugin with the following listener
```java
@EventHandler
void onBlockRedstoneEvent(BlockRedstoneEvent event){
    plugin.getLogger().log(Level.INFO, event.getBlock().toString())
}

```

Then make a tripwire contraption (Place tripwire hooks, and strings connecting the two hooks, the connection has to be a straight line)

After that, go into the tripwire and see the logged messages

### Plugin and Datapack List

Only a testplugin with the above mentioned listener

### Paper version

This server is running Paper version git-Paper-176 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 517f8fb)
You are running the latest version

### Other

_No response_

### PR DESCRIPTION
**Pull request by Lulu13022002**
Original: https://github.com/PaperMC/Paper/pull/9724

Closes https://github.com/PaperMC/Paper/issues/9714

### CODE REVIEW

File: paper-server/patches/sources/net/minecraft/world/level/block/TripWireHookBlock.java.patch [hunk 1]
```diff
@@ -1,21 +1,52 @@
 --- a/net/minecraft/world/level/block/TripWireHookBlock.java
 +++ b/net/minecraft/world/level/block/TripWireHookBlock.java
-@@ -173,9 +_,18 @@
+@@ -166,21 +_,48 @@
+             flag2 &= i > 1;
+             flag3 &= flag2;
+             BlockState blockState1 = block.defaultBlockState().trySetValue(ATTACHED, Boolean.valueOf(flag2)).trySetValue(POWERED, Boolean.valueOf(flag3));
++            boolean cancelledEmitterHook = false, cancelledReceiverHook = false; // Paper - Call BlockRedstoneEvent properly
++            boolean wasPowered = flag1, willBePowered = flag3; // Paper - OBFHELPER
```
Comment (lynxplay) [inline paper-server/patches/sources/net/minecraft/world/level/block/TripWireHookBlock.java.patch:21]: These should diff the actual final assignment of the values, otherwise this kind of diff does not *really* help during an update (e.g. if flag3 becomes flag4, the diff *might* still apply and the developer might not notice.

File: paper-server/patches/sources/net/minecraft/world/level/block/TripWireHookBlock.java.patch [hunk 2]
```diff
@@ -1,21 +1,52 @@
...
+             if (i > 0) {
+                 BlockPos blockPosx = pos.relative(direction, i);
++                // Paper start - Call BlockRedstoneEvent properly
++                if (wasPowered != willBePowered) {
++                    int newCurrent = willBePowered ? 15 : 0;
++                    org.bukkit.event.block.BlockRedstoneEvent redstoneEvent = new org.bukkit.event.block.BlockRedstoneEvent(org.bukkit.craftbukkit.block.CraftBlock.at(level, blockPosx), wasPowered ? 15 : 0, newCurrent);
++                    level.getCraftServer().getPluginManager().callEvent(redstoneEvent);
```
Comment (lynxplay) [inline paper-server/patches/sources/net/minecraft/world/level/block/TripWireHookBlock.java.patch]: callEvent();

File: paper-server/patches/sources/net/minecraft/world/level/block/TripWireHookBlock.java.patch [hunk 3]
```diff
@@ -1,21 +1,52 @@
...
++                    if (redstoneEvent.getNewCurrent() != newCurrent) {
++                        cancelledReceiverHook = true;
```
Comment (lynxplay) [inline paper-server/patches/sources/net/minecraft/world/level/block/TripWireHookBlock.java.patch]: `cancelledReceiverHook = redstoneEvent.getNewCurrent() != newCurrent;`
saves us a random if and imo is a fine change for such a readable expression.

File: paper-server/patches/sources/net/minecraft/world/level/block/TripWireHookBlock.java.patch [hunk 4]
```diff
@@ -1,21 +1,52 @@
...
-+            if (eventRedstone.getNewCurrent() > 0) {
-+                return;
+-            }
++                } // Paper - Call BlockRedstoneEvent properly
++            }
++            // Paper start - Call BlockRedstoneEvent properly
++            if (wasPowered != willBePowered) {
++                int newCurrent = willBePowered ? 15 : 0;
++                org.bukkit.event.block.BlockRedstoneEvent eventRedstone = new org.bukkit.event.block.BlockRedstoneEvent(org.bukkit.craftbukkit.block.CraftBlock.at(level, pos), wasPowered ? 15 : 0, newCurrent);
++                level.getCraftServer().getPluginManager().callEvent(eventRedstone);
```
Comment (lynxplay) [inline paper-server/patches/sources/net/minecraft/world/level/block/TripWireHookBlock.java.patch]: Same two comments as above. callEvent() and `if(bool) a = true` being a weird thing.

**Review by lynxplay — CHANGES_REQUESTED** [review]
Tested and works, just nitpicks (especially around the obfhelpers, the other is whatever)

**Review by lynxplay — APPROVED** [review]

**Review by Machine-Maker — APPROVED** [review]
