### PR TITLE
Teleport rework

### LINKED ISSUE #10201: Teleporting an entity resets its velocity
### Expected behavior

Moving minecart:
Using `/execute at <minecart> run tp <minecart> ~10 ~ ~` with a moving minecart should quickly move it 10 blocks east, before it would continue to move like normal (works with normal vanilla Minecraft)

Falling creeper:
Executing `/execute at <creeper> run tp <creeper> ~ ~ ~` on a creeper that is falling from the sky should leave it falling like nothing happened, because it doesn't modify the creepers position at all (also works fine with vanilla Minecraft)

### Observed/Actual behavior

Moving minecart:
The minecart is quickly moved 10 blocks east, but it then stops, completely losing its momentum.

Falling creeper:
The creeper stops mid air, before starting to fall again.

### Steps/models to reproduce

1. Create a default PaperMC 1.20.4 minecraft server.
2. Log on to the server and have a creeper stand on a block high in the air.
3. Knock the creeper down, execute `/execute at <creeper> run tp <creeper> ~ ~ ~`, and watch it stop mid air, before starting to fall again.
4. Build a track with powered rails and have a minecart move on it from north to south.
5. Execute `/execute at <minecart> run tp <minecart> ~10 ~ ~`, and watch the minecart quickly move 10 blocks forward, before it just stops

### Plugin and Datapack List

None.

### Paper version

[13:36:23 INFO]: This server is running Paper version git-Paper-389 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 848a396)

### Other

Velocity seems to be reset for any entity that is teleportet EXCEPT players.
```[tasklist]
### Tasks
```

### LINKED ISSUE #10792: Retain passengers flag is ignored when teleporting an entity with passengers to a location with a null world
### Expected behavior

When an entity with passengers is teleported to a location with a null world, it is teleported successfully, retaining its passengers. This is consistent with the behaviour of teleporting an entity with no passengers to a location with a null world.

### Observed/Actual behavior

The teleport fails.

### Steps/models to reproduce

```kotlin
val vehicle = player.world.spawn(player.location, ItemDisplay::class.java) {
    it.addPassenger(player)
}

// at some point later
vehicle.teleport(Location(null, 0.0, 0.0, 0.0, 0.0, 0.0), TeleportFlag.EntityState.RETAIN_PASSENGERS)
```

### Plugin and Datapack List

None other than the minimum to reproduce with the above code

### Paper version

This server is running Paper version 1.20.6-97-master@377733d (2024-05-24T18:03:46Z) (Implementing API version 1.20.6-R0.1-SNAPSHOT)

### Other

_No response_

### LINKED ISSUE #12317: EntityTeleportEvent fires twice when entity teleports
### Expected behavior

The EntityTeleportEvent event fires once when an entity teleports, with for example the /minecraft:tp command.

### Observed/Actual behavior

The EntityTeleportEvent event fires twice when an entity teleports.

### Steps/models to reproduce

I used a plugin called ExecutableEvents that utilizes this event. It allows you to fire commands when one of these events happen. According to the plugin developer, this does indeed use the EntityTeleportEvent event and fires twice.

### Plugin and Datapack List

Image

Image

### Paper version

[10:31:55 INFO]: Checking version, please wait...
[10:31:55 INFO]: This server is running Paper version 1.21.4-211-main@6ea4202 (2025-03-13T11:49:31Z) (Implementing API version 1.21.4-R0.1-SNAPSHOT)
You are 1 version(s) behind
Download the new version at: https://papermc.io/downloads/paper
Previous version: 1.21.4-187-1d5e5a5 (MC: 1.21.4)

### Other

Plugin utilized to find this out: ExecutableEvents by Ssomar

One of the plugin devs shared these screenshots with me:

Image

Image

### LINKED ISSUE #12361: Player abilities are reset when teleport across dimensions
### Expected behavior

Abilities shouldn't change
If the player is in survival or adventure mode and are able to fly, that behavior should persist across dimension teleports

### Observed/Actual behavior

When teleporting across dimensions, the abilities are reevaluated

For reference
- `CraftPlayer#teleport` calls `PlayerList#respawn` _L1511_
- `PlayerList#respawn` calls `PlayerList#restoreFrom` _L2052_
- `PlayerList#restoreFrom` calls `ServerPlayerGameMode#setGameModeForPlayer` _L93_

### Steps/models to reproduce

1. Set the player's game mode to survival or adventure
2. Allow the player to fly (Player#setAllowFlight)
3. Teleport the player into a different dimension **via Player#teleportAsync** _important_
4. Player is not able to fly anymore

### Plugin and Datapack List

plugins: Tweaks
datapacks: [vanilla (built-in)], [file/bukkit (world)], [paper (built-in)]

### Paper version

This server is running Paper version 1.21.4-222-main@9b1798d (2025-03-27T13:35:40Z) (Implementing API version 1.21.4-R0.1-SNAPSHOT)

### Other

This is a problem because the PlayerChangedWorldEvent is called after the player is respawned, meaning you may receive a wrong value when checking the player's ability to fly

In my specific case, I persist the player's flight state and ability to fly on dimension change to be able to restore those values later when the player enters that specific world again
(basically per world fly state)

### LINKED ISSUE #12696: Cancelling PlayerTeleportEvent when farmland block converts to dirt makes the player instantly die
### Expected behavior

When farmland block converts to a dirt block and a player is standing on it, cancelling PlayerTeleportEvent shouldn't cause the player to instantly die, but instead either not fire the PlayerTeleportEvent at all when pushing the player up or add another teleport cause (as right now the teleport cause is unknown) and make it so it cannot be cancelled (or just make it so the player doesn't die if cancelled).

### Observed/Actual behavior

When farmland block converts to a dirt block and a player is standing on it and the PlayerTeleportEvent gets cancelled the player instantly dies (teleports in void?).

### Steps/models to reproduce

1. Make a dummy plugin which cancels PlayerTeleportEvent
2. Give yourself a farmland block
3. Jump on it

### Plugin and Datapack List

Dummy plugin for cancelling the PlayerTeleportEvent

### Paper version

This server is running Paper version 1.21.4-232-ver/1.21.4@12d8fe0 (2025-06-09T10:15:42Z) (Implementing API version 1.21.4-R0.1-SNAPSHOT)
You are running the latest version
Previous version: 1.21-DEV-81bc9ba (MC: 1.21)

### Other

This did not happen on version 1.21.1, but only when we switched to 1.21.4.

### LINKED ISSUE #12872: Teleport flags not retaining passengers on cross-world travel
### Expected behavior

I use teleport flag to retain passengers and passengers are kept when you teleport from 1 world to another. (it works fine for teleporting in the same world)

### Observed/Actual behavior

It literally does nothing. Teleport effects called with the retain passengers teleport flag, if the player has passengers and they are being teleported to a new world, do absolutely nothing. I get no errors, no chat messages, the player just doesn't get teleported.

### Steps/models to reproduce

1. Create a new papermc server (I tested it on 1.21.4 and 1.21.8)
2. Make a new paper plugin and somewhere in there (probably a command/event) teleport the player to a location in the nether (or any alternate world) using teleport flag retain passengers
3. Run the plugin & add a passenger to the player, then run the command/event to teleport the player.
4. Watch as nothing happens

### Plugin and Datapack List

Image

### Paper version

1.21.8-R0.1-SNAPSHOT

### Other

_No response_

### LINKED ISSUE #13078: Cannot teleport entity with passanger
### Expected behavior

In vanilla, with the command /teleport, I can teleport entities with passengers.

### Observed/Actual behavior

In code, using the Entity::teleport method, I can't teleport an entity with passengers.

### Steps/models to reproduce

check Actual behavior

### Plugin and Datapack List

not related

### Paper version

not related

### Other

CraftEntity
```java
public boolean teleport(Location location, TeleportCause cause) {
    if (entity.passenger != null || entity.dead) {
        return false; //<---
    }
...
}
```
Minecraft Entity
```java
public boolean teleportTo(...) {
...
    this.moveTo(d0, d1, d2, f, f2);
    this.teleportPassengers(); //<---
    this.setYHeadRot(f);
}
```

### PR DESCRIPTION
**Pull request by Owen1212055**
Fixes: #12872
Fixes: #13078
Fixes: #12361
Fixes: #12361
Fixes: #10792
Fixes: #10201

### CODE REVIEW

File: paper-server/src/main/java/org/bukkit/craftbukkit/CraftRegionAccessor.java [hunk 1]
```diff
@@ -375,7 +375,7 @@ public <T extends Entity> T addEntity(T entity) {
         Preconditions.checkArgument(!entity.isInWorld(), "Entity has already been added to a world");
         net.minecraft.world.entity.Entity nmsEntity = ((CraftEntity) entity).getHandle();
         if (nmsEntity.level() != this.getHandle().getLevel()) {
-            nmsEntity = nmsEntity.teleport(new TeleportTransition(this.getHandle().getLevel(), nmsEntity, TeleportTransition.DO_NOTHING));
+            throw new IllegalArgumentException(entity + " wasn't created with this world, you must create the entity with the world you want to add it to.");
         }
```
Comment (Doc94) [inline paper-server/src/main/java/org/bukkit/craftbukkit/CraftRegionAccessor.java:379]: i feel a Precondition can be good here if now this throw an exception.
```suggestion
        Preconditions.checkArgument(nmsEntity.level() == this.getHandle().getLevel(), "%s wasn't created with this world, you must create the entity with the world you want to add it to.", entity);
```

**Review by kennytv — COMMENTED** [review]
The deprecation docs and/or method docs should be more specific about what the teleport behavior is now, and what to call if you always want to eject passengers

**Comment by Doc94** [comment]
Maybe this can consider https://github.com/PaperMC/Paper/issues/13186 and https://github.com/PaperMC/Paper/issues/13023 ? in teory the vanilla teleport consider that limit in bounds for limit but the api ignore that... if not can check in my draft https://github.com/PaperMC/Paper/pull/13076 when this is merged (for avoid merge conflicts)

File: paper-server/patches/sources/net/minecraft/server/network/ServerGamePacketListenerImpl.java.patch [hunk 2]
```diff
@@ -376,7 +376,7 @@
  
              this.player
 -                .absSnapTo(
-+                 .snapTo( // Paper - Fix Entity Teleportation and cancel velocity if teleported
++                 .absSnapTo(
```
Comment (Warriorrrr) [inline paper-server/patches/sources/net/minecraft/server/network/ServerGamePacketListenerImpl.java.patch]: This bit of diff can be fully removed, as the only leftover changed part seems to be a single space

File: paper-server/src/main/java/org/bukkit/craftbukkit/CraftRegionAccessor.java (hunk 1 above)
Comment (Lulu13022002) [reply paper-server/src/main/java/org/bukkit/craftbukkit/CraftRegionAccessor.java:379]: Better to not evaluate that string earlier.

**Review by kennytv — APPROVED** [review]

**Review by lynxplay — APPROVED** [review]
