### PR TITLE
Fix #11887

### LINKED ISSUE #11887: IllegalStateException when trying to create a blockState from a Material
### Stack trace

```log
Error occurred while enabling Zones v1.0-SNAPSHOT (Is it up to date?)
java.lang.IllegalStateException: The blockState must be placed to call this method
	at com.google.common.base.Preconditions.checkState(Preconditions.java:513) ~[guava-33.3.1-jre.jar:?]
	at org.bukkit.craftbukkit.block.CraftBlockState.requirePlaced(CraftBlockState.java:332) ~[paper-1.21.4.jar:1.21.4-72-daddcf6]
	at org.bukkit.craftbukkit.block.CraftBlockState.getWorld(CraftBlockState.java:101) ~[paper-1.21.4.jar:1.21.4-72-daddcf6]
	at org.bukkit.craftbukkit.block.CraftBlockEntityState.<init>(CraftBlockEntityState.java:53) ~[paper-1.21.4.jar:1.21.4-72-daddcf6]
	at org.bukkit.craftbukkit.block.CraftMovingPiston.<init>(CraftMovingPiston.java:10) ~[paper-1.21.4.jar:1.21.4-72-daddcf6]
	at org.bukkit.craftbukkit.block.CraftBlockStates$BlockEntityStateFactory.createBlockState(CraftBlockStates.java:115) ~[paper-1.21.4.jar:1.21.4-72-daddcf6]
	at org.bukkit.craftbukkit.block.CraftBlockStates$BlockEntityStateFactory.createBlockState(CraftBlockStates.java:107) ~[paper-1.21.4.jar:1.21.4-72-daddcf6]
	at org.bukkit.craftbukkit.block.CraftBlockStates$BlockEntityStateFactory.createBlockState(CraftBlockStates.java:89) ~[paper-1.21.4.jar:1.21.4-72-daddcf6]
	at org.bukkit.craftbukkit.block.CraftBlockStates.getBlockState(CraftBlockStates.java:308) ~[paper-1.21.4.jar:1.21.4-72-daddcf6]
	at org.bukkit.craftbukkit.block.CraftBlockStates.getBlockState(CraftBlockStates.java:294) ~[paper-1.21.4.jar:1.21.4-72-daddcf6]
	at org.bukkit.craftbukkit.block.CraftBlockStates.getBlockState(CraftBlockStates.java:283) ~[paper-1.21.4.jar:1.21.4-72-daddcf6]
	at org.bukkit.craftbukkit.block.data.CraftBlockData.createBlockState(CraftBlockData.java:745) ~[paper-1.21.4.jar:1.21.4-72-daddcf6]
	at zones-1.0-dev.jar/de.t14d3.zones.utils.Types.populateTypes(Types.java:60) ~[zones-1.0-dev.jar:?]
	at zones-1.0-dev.jar/de.t14d3.zones.Zones.onEnable(Zones.java:79) ~[zones-1.0-dev.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.21.4.jar:1.21.4-72-daddcf6]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.21.4.jar:1.21.4-72-daddcf6]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:655) ~[paper-1.21.4.jar:1.21.4-72-daddcf6]
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:604) ~[paper-1.21.4.jar:1.21.4-72-daddcf6]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:743) ~[paper-1.21.4.jar:1.21.4-72-daddcf6]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:488) ~[paper-1.21.4.jar:1.21.4-72-daddcf6]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:322) ~[paper-1.21.4.jar:1.21.4-72-daddcf6]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1163) ~[paper-1.21.4.jar:1.21.4-72-daddcf6]
	at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:310) ~[paper-1.21.4.jar:1.21.4-72-daddcf6]
```

### Plugin and Datapack List

[Zones](https://github.com/T14D3/Zones/tree/d50162db8cba873ae7e05732de86bda85d1f1da9)

### Actions to reproduce (if known)

Try to create a blockState from Material ~~in onEnable of a plugin~~ Edit: Anywhere

Edit2: Caused by trying to create a blockState for a MOVING_PISTON

### Paper version

This server is running Paper version 1.21.4-72-main@daddcf6 (2025-01-02T08:17:56Z) (Implementing API version 1.21.4-R0.1-SNAPSHOT)

### Other

_No response_

### PR DESCRIPTION
**Pull request by masmc05**
Closes #11887
Fixes both the wrapper exception for non-placed tile entities and creation of a craft moving piston

### CODE REVIEW

File: paper-server/src/main/java/org/bukkit/craftbukkit/block/CraftBlockEntityState.java [hunk 1]
```diff
@@ -50,7 +50,8 @@ public CraftBlockEntityState(World world, T tileEntity) {
             if (thr instanceof ThreadDeath) {
                 throw (ThreadDeath)thr;
             }
-            throw new RuntimeException("Failed to read BlockState at: world: " + this.getWorld().getName() + " location: (" + this.getX() + ", " + this.getY() + ", " + this.getZ() + ")", thr);
+            String worldName = world == null ? "null" : world.getName();
+            throw new RuntimeException("Failed to read BlockState at: world: " + worldName + " location: (" + this.getX() + ", " + this.getY() + ", " + this.getZ() + ")", thr);
```
Comment (Machine-Maker) [inline paper-server/src/main/java/org/bukkit/craftbukkit/block/CraftBlockEntityState.java]: No need to show the location at all if it's not placed in the world. The purpose of our change to make it have the world/position is for debugging in-world issues. Not important for unplaced states.

**Review by Machine-Maker — DISMISSED** [review]

File: paper-server/src/main/java/org/bukkit/craftbukkit/block/CraftBlockEntityState.java (hunk 1 above)
Comment (masmc05) [reply paper-server/src/main/java/org/bukkit/craftbukkit/block/CraftBlockEntityState.java]: Changed it

**Review by lynxplay — APPROVED** [review]
