### PR TITLE
Change thrown trident item to use copy of ItemStack of count 1

### LINKED ISSUE #13390: Stacked tridents with increased max_stack_size are duplicated when thrown and picked up
### Expected behavior

Only one trident item would be picked up.

### Observed/Actual behavior

The player picks up the number of tridents held at the time of throwing.

### Steps/models to reproduce

Give yourself a trident with a greater than one max stack size. (Note: You also need to remove the max damage component to change max stack size)
`/give @p minecraft:trident[minecraft:max_stack_size=64,!minecraft:max_damage] 64`

In survival mode, throw the trident into the ground.
Pick up the trident.

### Plugin and Datapack List

FancyNpcs 
ProtocolLib
Custom plugin, no impact on this functionality.

Datapacks:
Vanilla, Bukkit, Paper.

### Paper version

This server is running Paper version 1.21.11-38-main@4446f17 (2025-12-09T22:51:57Z) (Implementing API version 1.21.11-R0.1-SNAPSHOT)
You are 1 version(s) behind
Download the new version at: https://papermc.io/downloads/paper
Previous version: 1.21.10-105-1f31ee5 (MC: 1.21.10)

### Other

https://github.com/PaperMC/Paper/blob/e5e2c50ed3f7a6e4dbe7451c089cb1ad3f77f8f9/paper-server/patches/sources/net/minecraft/world/item/TridentItem.java.patch#L27C62-L27C67

`thrownTrident.pickupItemStack = stack.copy(); // SPIGOT-4511 update since damage call moved`

Should be using `itemstack` variable created here 
https://github.com/PaperMC/Paper/blob/e5e2c50ed3f7a6e4dbe7451c089cb1ad3f77f8f9/paper-server/patches/sources/net/minecraft/world/item/TridentItem.java.patch#L12

### PR DESCRIPTION
**Pull request by ColinNason**
Fixes https://github.com/PaperMC/Paper/issues/13390

New change uses the defined `itemStack` variable to set the trident pick up item. The `itemStack` variable is a fixed value of 1.

The `hurtWithoutBreaking` call is also switched over, this is to allow regular tridents to still take durability damage.

### CODE REVIEW

File: paper-server/patches/sources/net/minecraft/world/item/TridentItem.java.patch [hunk 1]
```diff
@@ -22,9 +22,9 @@
 +                            }
 +                            ThrownTrident thrownTrident = tridentDelayed.projectile(); // Paper - PlayerLaunchProjectileEvent
 +                            if (event.shouldConsume()) {
-+                                stack.hurtWithoutBreaking(1, player); // Paper - PlayerLaunchProjectileEvent
++                                itemStack.hurtWithoutBreaking(1, player); // Paper - PlayerLaunchProjectileEvent // Paper use itemStack; pickup item damage
```
Comment (lynxplay) [inline paper-server/patches/sources/net/minecraft/world/item/TridentItem.java.patch]: We are long hardforked from spigot, no need to add paper comments again, this code is already in a diff block.

**Review by lynxplay — APPROVED** [review]

**Review by Owen1212055 — APPROVED** [review]
