### PR TITLE
[Fix] Prevent dupe via PlayerDropItemEvent when using /give

### LINKED ISSUE #12609: `/give` duplicates items when `PlayerDropItemEvent` is cancelled.
### Expected behavior

When a plugin cancels PlayerDropItemEvent, the item should not be duplicated

### Observed/Actual behavior

Using /give on a player whose PlayerDropItemEvent is cancelled causes the player to receive double the items.

### Steps/models to reproduce

1. Cancel PlayerDropItemEvent
2. use /give

### Plugin and Datapack List

none

### Paper version

[01:23:45 INFO]: Checking version, please wait...
[01:23:45 INFO]: This server is running Paper version 1.21.5-103-main@2ba1675 (2025-05-29T12:14:46Z) (Implementing API version 1.21.5-R0.1-SNAPSHOT)
You are running the latest version
Previous version: 1.21-91-3c8a7fe (MC: 1.21)

### Other

_No response_

### PR DESCRIPTION
**Pull request by Rodald**
Fixes #12609 

Cancelling PlayerDropItemEvent would cause items from /give to be duplicated

### CODE REVIEW

File: paper-server/patches/sources/net/minecraft/server/commands/GiveCommand.java.patch [hunk 1]
```diff
@@ -8,7 +8,31 @@
...
          int i = maxStackSize * 100;
          if (count > i) {
-@@ -95,11 +_,11 @@
+@@ -65,8 +_,10 @@
+                     i1 -= min;
+                     ItemStack itemStack1 = item.createItemStack(min, false);
+                     boolean flag = serverPlayer.getInventory().add(itemStack1);
++
++                    // Paper start - Fix PlayerDropItemEvent dupe on /give
++                    ItemEntity itemEntity = serverPlayer.drop(itemStack1, false, false, false, null);
```
Comment (Doc94) [inline paper-server/patches/sources/net/minecraft/server/commands/GiveCommand.java.patch]: this broke how that works you replace two drop calls one with itemStack and another with itemStack1 for a method where only itemStack1 is used.

better modify the current calls for add the other params and include the // Paper

but im unsure if the fix is avoid the event or improvement the fallback what sounds a little hard because the method dont know from where come the drop...

Comment (Doc94) [reply paper-server/patches/sources/net/minecraft/server/commands/GiveCommand.java.patch]: reading the event and [this](https://github.com/PaperMC/Paper/blob/main/paper-server/src/main/java/org/bukkit/craftbukkit/entity/CraftHumanEntity.java#L860) make sense not call the event then the only thing you need is override the two calls here

**Comment by Rodald** [comment]
I hope that fixes the itemStack and itemStack1 issue.

Please let me know if further changes are needed :D

File: paper-server/patches/sources/net/minecraft/server/commands/GiveCommand.java.patch [hunk 2]
```diff
@@ -8,6 +8,28 @@
...
          int i = maxStackSize * 100;
          if (count > i) {
+@@ -66,7 +_,9 @@
+                     ItemStack itemStack1 = item.createItemStack(min, false);
+                     boolean flag = serverPlayer.getInventory().add(itemStack1);
+                     if (flag && itemStack1.isEmpty()) {
+-                        ItemEntity itemEntity = serverPlayer.drop(itemStack, false);
++                        // Paper start - Fix PlayerDropItemEvent dupe on /give
++                        ItemEntity itemEntity = serverPlayer.drop(itemStack, false, false, false, null);
++                        // Paper end - Fix PlayerDropItemEvent dupe on /give
```
Comment (Warriorrrr) [inline paper-server/patches/sources/net/minecraft/server/commands/GiveCommand.java.patch]: Paper start/end comments aren't necessary for a one line change, you can just put a comment at the end of the line. I think the comment itself should also be changed to better describe the change, something along the lines of not firing the drop item event for the give command.

**Comment by Rodald** [comment]
I updated the comments to follow Paper's formatting guidelines.
Let me know if there's anything else I should improve.

**Review by Doc94 — APPROVED** [review]

**Review by Warriorrrr — APPROVED** [review]

**Review by Machine-Maker — APPROVED** [review]
