### PR TITLE
Fix help.yml index-topics not working for non-console senders

### LINKED ISSUE #13106: IndexHelpTopic doesn't work for players
### Expected behavior

If I configure the `help.yml` like this:

```yml
command-topics-in-master-index: true

general-topics:
  Rules:
    shortText: Rules of the server
    fullText: |
      &61. Be kind to your fellow players.
      &B2. No griefing.
      &D3. No swearing.

amended-topics:
  /ban:
    shortText: Ban a player
  /ban-ip:
    shortText: Ban an IP address
  /banlist:
    shortText: Show active bans

index-topics:
  Ban:
    shortText: Player banning commands
    preamble: |
      &eModerator tools – do not abuse these commands.
    commands:
    - Rules
    - /ban
    - /ban-ip
    - /banlist
```

the player should see the topic Ban if he executes /help or /?.

### Observed/Actual behavior

The topic is hidden for the player. The console can see the topic.

### Steps/models to reproduce

copy & paste the help.yml in your server folder. Start the server and try /help.

### Plugin and Datapack List

No plugins and no datapacks

### Paper version

version
[16:02:53 INFO]: Checking version, please wait...
[16:02:53 INFO]: This server is running Paper version 1.21.8-DEV (2025-09-28T13:50:56Z) (Implementing API version 1.21.8-R0.1-SNAPSHOT)
You are running a development version without access to version information

### Other

CustomIndexHelpTopic converts the string to late to the topic. The topic will be skipped because of the list size of 0 of the custom index topic. 

I tried it like this and it worked:

```java
public CustomIndexHelpTopic(HelpMap helpMap, String name, String shortText, String permission, List<String> futureTopics, String preamble) {
        super(name, shortText, permission, new HashSet<>(), preamble);
        this.helpMap = helpMap;

        List<HelpTopic> topics = new LinkedList<>();
        for (String futureTopic : futureTopics) {
            HelpTopic topic = this.helpMap.getHelpTopic(futureTopic);
            if (topic != null) {
                topics.add(topic);
            }
        }
        this.setTopicsCollection(topics);
    }
```

### PR DESCRIPTION
**Pull request by roro1506HD**
Closes #13106

### CODE REVIEW

File: paper-server/src/main/java/org/bukkit/craftbukkit/help/CustomIndexHelpTopic.java [hunk 1]
```diff
@@ -7,6 +7,7 @@
 import org.bukkit.help.HelpMap;
 import org.bukkit.help.HelpTopic;
 import org.bukkit.help.IndexHelpTopic;
+import org.jetbrains.annotations.NotNull;
```
Comment (Toffikk) [inline paper-server/src/main/java/org/bukkit/craftbukkit/help/CustomIndexHelpTopic.java:10]:
```suggestion
import org.jspecify.annotations.NonNull;
```
You should use the jspecify annotations in this case

File: paper-server/src/main/java/org/bukkit/craftbukkit/help/CustomIndexHelpTopic.java [hunk 2]
```diff
@@ -18,8 +19,21 @@ public CustomIndexHelpTopic(HelpMap helpMap, String name, String shortText, Stri
         this.futureTopics = futureTopics;
     }
 
+    @Override
+    public boolean canSee(@NotNull final CommandSender sender) {
```
Comment (Toffikk) [inline paper-server/src/main/java/org/bukkit/craftbukkit/help/CustomIndexHelpTopic.java:23]:
```suggestion
    public boolean canSee(@NonNull final CommandSender sender) {
```

File: paper-server/src/main/java/org/bukkit/craftbukkit/help/CustomIndexHelpTopic.java (hunk 1 above)
Comment (roro1506HD) [reply paper-server/src/main/java/org/bukkit/craftbukkit/help/CustomIndexHelpTopic.java:10]: Kept jetbrains one since the parent method also has a jetbrains one and I didn't feel like it was a needed change for this PR. Can update this one and parent's ones if needed though.

Comment (Toffikk) [reply paper-server/src/main/java/org/bukkit/craftbukkit/help/CustomIndexHelpTopic.java:10]: Then i suppose this can be kept as-is, paper will replace them later when they merge the checkstyle pr

**Review by jpenilla — APPROVED** [review]

**Review by Owen1212055 — APPROVED** [review]
