### PR TITLE
Fix inconsistencies between offline/online spawn position getter

### LINKED ISSUE #7860: Player vs OfflinePlayer getBedSpawnLocation
### Expected behavior

When calling `getBedSpawnLocation` on an instance of CraftPlayer or CraftOfflinePlayer the result should be the same (or the discrepancy should be documented and predictable)

### Observed/Actual behavior

They are different as shown here
```
test
[16:05:20 INFO]: [Paper-Test-Plugin] [STDOUT] online: true
[16:05:20 INFO]: [Paper-Test-Plugin] [STDOUT] spawn: Location{world=CraftWorld{name=world_nether},x=-7.5,y=89.0,z=-18.5,pitch=0.0,yaw=0.0}
[16:05:22 INFO]: Machine_Maker lost connection: Disconnected
[16:05:22 INFO]: Machine_Maker left the game
test
[16:05:27 INFO]: [Paper-Test-Plugin] [STDOUT] online: false
[16:05:27 INFO]: [Paper-Test-Plugin] [STDOUT] spawn: Location{world=CraftWorld{name=world_nether},x=-8.0,y=89.0,z=-18.0,pitch=0.0,yaw=0.0}
```

### Steps/models to reproduce

1. Set your spawn in the world
2. Log the player's bed spawn loc
3. log out
4. get the instance of offlineplayer
5. log the bed spawn loc

### Plugin and Datapack List

none

### Paper version

af3b3778f6de06af48de08d41a43565d3ff19976

### Other

_No response_

### LINKED ISSUE #12338: Abnormal API behavior when obtaining the player's respawn position causes Anchor's charging to be consumed
### Expected behavior

When `player.getBedSpawnLocation()` or `player.getRespawnLocation()` is called, the API will be running as usual if the player's respawn block is Anchor

### Observed/Actual behavior

The API works normally, but Anchor's charging is consumed abnormally

### Steps/models to reproduce

1. Go to nether
2. Place an Anchor and charge it, then right-click to set the respawn point.
3. Call API: `player.getBedSpawnLocation()` or `player.getRespawnLocation()`
4. Unexpected behavior can be observed: Anchor charging decreases

### Plugin and Datapack List

[17:46:08 INFO]: ℹ Server Plugins (3):
[17:46:08 INFO]: Bukkit Plugins:
[17:46:08 INFO]: - LetsExpand, PlugManX, spark

### Paper version

version
[17:46:28 INFO]: Checking version, please wait...
[17:46:30 INFO]: This server is running Paper version 1.21.4-221-main@c467df9 (2025-03-24T00:18:41Z) (Implementing API version 1.21.4-R0.1-SNAPSHOT)
You are running the latest version
Previous version: 1.21.4-DEV-bc157c7 (MC: 1.21.4)

### Other

I observed the javadoc and found no text describing this behavior, and I suspect it might be an unexpected behavior rather than a deliberate design.

### PR DESCRIPTION
**Pull request by Lulu13022002**
Original: https://github.com/PaperMC/Paper/pull/8243
Also deprecated the old HumanEntity#getPotentialRespawnLocation since it doesn't track the respawn angle.

### CODE REVIEW

File: paper-api/src/main/java/org/bukkit/OfflinePlayer.java [hunk 1]
```diff
@@ -290,13 +291,26 @@ public default BanEntry banPlayer(@Nullable String reason, @Nullable java.util.D
...
+     * Gets the Location where the player will spawn at, {@code null} if they
      * don't have a valid respawn point.
      *
-     * @return respawn location if exists, otherwise null.
+     * @param load load the current location to retrieve the exact position of the spawn block
+     *             and check if this position is still valid or not
+     * @return respawn location if exists, otherwise {@code null}.
      */
     @Nullable
-    public Location getRespawnLocation();
```
Comment (Strokkur424) [inline paper-api/src/main/java/org/bukkit/OfflinePlayer.java:296]: I am wondering, what really is the rule for interfaces and explicit `public` modifiers? I have seen files/PRs with and I have seen files/PRs without.

File: paper-api/src/main/java/org/bukkit/entity/Player.java [hunk 2]
```diff
@@ -560,15 +560,11 @@ public interface Player extends HumanEntity, Conversable, OfflinePlayer, PluginM
     @Deprecated(since = "1.20.4")
     public Location getBedSpawnLocation();
 
-    /**
-     * Gets the Location where the player will spawn at, null if they
-     * don't have a valid respawn point.
-     *
-     * @return respawn location if exists, otherwise null.
-     */
```
Comment (Strokkur424) [inline paper-api/src/main/java/org/bukkit/entity/Player.java]: The Javadocs have been removed on this method. Is this intentional, or are you going to be adding different Javadocs soon?

Comment (456dev) [reply paper-api/src/main/java/org/bukkit/entity/Player.java]: iirc it should now inherit from offline player?

File: paper-api/src/main/java/org/bukkit/OfflinePlayer.java (hunk 1 above)
Comment (FireInstall) [reply paper-api/src/main/java/org/bukkit/OfflinePlayer.java:296]: As far as I know, it was an unnecessary rule enforced by spigot.

File: paper-api/src/main/java/org/bukkit/entity/Player.java (hunk 2 above)
Comment (electronicboy) [reply paper-api/src/main/java/org/bukkit/entity/Player.java]: I don't think JDs are inherited by default?

Comment (electronicboy) [reply paper-api/src/main/java/org/bukkit/entity/Player.java]: oh, no, nvm, they are, ineritDoc is for additive

**Comment by Lulu13022002** [comment]
This also fix Player#getRespawnLocation that consume the respawn anchor in the nether if binded

File: paper-api/src/main/java/org/bukkit/OfflinePlayer.java [hunk 3]
```diff
@@ -290,13 +291,26 @@ public default BanEntry banPlayer(@Nullable String reason, @Nullable java.util.D
...
-     * Gets the Location where the player will spawn at, null if they
+     * Gets the Location where the player will spawn at, {@code null} if they
+     * don't have a valid respawn point.
+     *
+     * @return respawn location if exists, otherwise {@code null}.
+     */
+    @Nullable
+    default Location getRespawnLocation() {
+        return this.getRespawnLocation(false); // keep old behavior for offline players
+    }
```
Comment (SoSeDiK) [inline paper-api/src/main/java/org/bukkit/OfflinePlayer.java]: Thoughts on deprecating this method (without overload) altogether?
`Player` extends `OfflinePlayer`, and both have different default chunk loading behavior, which is quite confusing (also would be nice to specify the default behavior in respective javadocs).

Comment (Lulu13022002) [reply paper-api/src/main/java/org/bukkit/OfflinePlayer.java]: I have updated the javadoc, not sure for the deprecation, i kinda expect offline player data to be less accurate than online by default. What i think is confusing is the fact that an online player extends an offline player in the api.

Comment (SoSeDiK) [reply paper-api/src/main/java/org/bukkit/OfflinePlayer.java]: > What i think is confusing is the fact that an online player extends an offline player in the api.

Yes, that was my concern. Technically, you can have `OfflinePlayer` object representing an online `Player` instance (`#getOfflinePlayer` too returns online player if present), so you may call the method on an offline player expecting not to load chunks, but they will load due to the object being an online player.

New devs might stumble upon this quirk and will have to account for it. Deprecation would require to explicitly specify the wanted behavior, but I don't have a strong feeling against leaving this as is.

File: paper-api/src/main/java/org/bukkit/OfflinePlayer.java [hunk 4]
```diff
@@ -290,13 +291,28 @@ public default BanEntry banPlayer(@Nullable String reason, @Nullable java.util.D
...
      * don't have a valid respawn point.
      *
-     * @return respawn location if exists, otherwise null.
+     * @param load load the current location to retrieve the exact position of the spawn block
+     *             and check if this position is still valid or not
+     * @return respawn location if exists, otherwise {@code null}.
      */
     @Nullable
-    public Location getRespawnLocation();
+    Location getRespawnLocation(boolean load);
```
Comment (lynxplay) [inline paper-api/src/main/java/org/bukkit/OfflinePlayer.java]: Not a fan of the param naming here.
loadAndValidate?

**Review by lynxplay — APPROVED** [review]
LGTM beyond the param name.

**Comment by JRoy** [comment]
This PR also fixes an issue where `getRespawnLocation` consumed a respawn anchor charge when it was called.

**Review by Machine-Maker — APPROVED** [review]

**Comment by FellowNeighbour** [comment]
Waiting for this to be merged into upstream so respawn anchors work properly with EssX

**Comment by NonSwag** [comment]
@notTamion just hinted me to this PR 
getPotentialRespawnPosition is in my opinion a misleading name since it returns the respawn point block location and not the location the player would _potentially_ respawn at
I opened a PR that introduces `getRespawnBlock` which is a more fitting name (probably going with `getRespawnBlockLocation` though)

**Comment by masmc05** [comment]
`getRespawnBlock` is a misleading name as the respawn location may not be linked to a block and may contain angle data, as you could define with `spawnpoint` command

**Comment by Leguan16** [comment]
Maybe `getDefinedRespawnLocation` and `getActualRespawnLocation` with the later doing the lookup.

File: paper-api/src/main/java/org/bukkit/OfflinePlayer.java [hunk 5]
```diff
@@ -290,13 +291,28 @@ public default BanEntry banPlayer(@Nullable String reason, @Nullable java.util.D
     // Paper end
 
     /**
-     * Gets the Location where the player will spawn at, null if they
+     * Gets the Location where the player will spawn at, {@code null} if they
+     * don't have a valid respawn point.
+     * <br>
+     * Unlike online players, the location if found will not be loaded by default.
```
Comment (Warriorrrr) [inline paper-api/src/main/java/org/bukkit/OfflinePlayer.java:293]: This note will be inherited by the player class which may seem confusing, we may want to have some javadocs in the player class override for this method still.

**Review by NoahvdAa — APPROVED** [review]
