### PR TITLE
Start discouraging world name use

### LINKED ISSUE #13765: No longer able to create worlds not in the (default) minecraft namespace
### Expected behavior

In Paper 1.21.x, it was possible to create worlds with a given namespace other than "minecraft".

### Observed/Actual behavior

In the 26.1.x alpha builds. This is no longer possible and instead throws `UnsupportedOperationException: Custom world keys not yet implemented`
Even though there is deprecation warning or otherwise.

### Steps/models to reproduce

```java
new org.bukkit.WorldCreator("level_name", new org.bukkit.NamespacedKey("namespace", "level_name");
// or
new org.bukkit.WorldCreator(new org.bukkit.NamespacedKey("namespace", "level_name");
```

### Plugin and Datapack List

N/A

### Paper version

26.1.1-14-dev/26.1@f6d2701

### Other

See: https://github.com/PaperMC/Paper/blob/2d6e82ec48799a2db584dc7881f78dcc65b8e8b3/paper-api/src/main/java/org/bukkit/WorldCreator.java#L61

### PR DESCRIPTION
**Pull request by jpenilla**
Also allows creating dimensions by key.

### CODE REVIEW

**Review by kennytv — APPROVED** [review]

File: paper-api/src/main/java/org/bukkit/Server.java [hunk 1]
```diff
@@ -793,11 +793,15 @@ default int getTicksPerAmbientSpawns() {
...
      *
-     * @param name the name of the world to retrieve
-     * @return a world with the given name, or null if none exists
+     * <p>This method is considered obsolete and is a candidate for future deprecation.
+     * Prefer using {@link #getWorld(NamespacedKey)}.</p>
+     *
+     * @param name the legacy Bukkit name of the world to retrieve
+     * @return a world with the given legacy Bukkit name, or null if none exists
      */
+    @ApiStatus.Obsolete
```
Comment (Lulu13022002) [inline paper-api/src/main/java/org/bukkit/Server.java:804]: What about Bukkit#getWorld(String) and its usage?
For example the mobcap command suggest world keys but wants a world name.

File: paper-server/patches/sources/net/minecraft/server/MinecraftServer.java.patch [hunk 2]
```diff
@@ -492,7 +493,7 @@
 +
 +                if (spawn != null) {
 +                    if (spawn.getWorld() != level.getWorld()) {
-+                        throw new IllegalStateException("Cannot set spawn point for " + levelData.getLevelName() + " to be in another world (" + spawn.getWorld().getName() + ")");
++                        throw new IllegalStateException("Cannot set spawn point for " + levelData.getLevelName() + " to be in another world (" + io.papermc.paper.util.MCUtil.getLevelName(level) + ")");
```
Comment (Lulu13022002) [inline paper-server/patches/sources/net/minecraft/server/MinecraftServer.java.patch:496]: That's not the right world.

File: paper-server/src/main/java/com/destroystokyo/paper/io/SyncLoadFinder.java [hunk 3]
```diff
@@ -71,7 +71,7 @@ public static JsonObject serialize() {
 
             final JsonObject worldData = new JsonObject();
 
-            worldData.addProperty("name", world.getWorld().getName());
+            worldData.addProperty("name", world.getWorld().getKey().toString());
```
Comment (Lulu13022002) [inline paper-server/src/main/java/com/destroystokyo/paper/io/SyncLoadFinder.java:74]: Should probably change the key too.

File: paper-server/src/main/java/io/papermc/paper/command/subcommands/EntityCommand.java [hunk 4]
```diff
@@ -85,18 +86,18 @@ private void listEntities(final CommandSender sender, final String[] args) {
...
             } else {
                 sender.sendMessage(text("Please specify the name of a world", RED));
                 sender.sendMessage(text("To do so without a filter, specify '*' as the filter", RED));
-                sender.sendMessage(text("Usage: /paper entity list [filter] [worldName]", RED));
+                sender.sendMessage(text("Usage: /paper entity list [filter] [worldKey]", RED));
                 return;
             }
             Map<Identifier, MutablePair<Integer, Map<ChunkPos, Integer>>> list = Maps.newHashMap();
-            @Nullable World bukkitWorld = Bukkit.getWorld(worldName);
+            @Nullable World bukkitWorld = Bukkit.getWorld(NamespacedKey.fromString(worldName));
```
Comment (Lulu13022002) [inline paper-server/src/main/java/io/papermc/paper/command/subcommands/EntityCommand.java:97]: fromString is nullable if someone is fancy this will throw a NPE, that's not the only unsafe use of it in this PR.

File: paper-api/src/main/java/org/bukkit/Server.java (hunk 1 above)
Comment (Lulu13022002) [reply paper-api/src/main/java/org/bukkit/Server.java:804]: Not resolved for the other usages, see for example the chunkinfo subcommand which suggest world keys but wants a world name.
