### PR TITLE
fix: inventory desync when interaction is cancelled

### LINKED ISSUE #12947: Interacting with a flower pot within the spawn protection area will generate virtual items
### Expected behavior

The quick-access inventory should not display these virtual flowers.

### Observed/Actual behavior

Interacting with a flower pot within the spawn protection area will generate virtual items

### Steps/models to reproduce

1. Keep the first slot of the player's quick-access inventory empty, and use the scroll wheel to switch to any of the slots from 2 to 9.
2. Then interact with a flower pot containing any type of flower within the spawn protection area.
3. The quick-access inventory will display virtual flowers.

### Plugin and Datapack List

null

### Paper version

paper1.21.8-28

### Other

https://github.com/PaperMC/Paper/issues/11012
Similar situations might be a vanilla issue, but I haven't tested it on vanilla.
It can also be reproduced on other types of region protection plugins.

### LINKED ISSUE #12954: Cancelling PlayerInteractEvent does not prevent item from being added to inventory
### Expected behavior

When cancelling PlayerInteractEvent, items added due to that event should not be added.

Example: When right-clicking a lodestone with a compass, a linked compass should not be added to the inventory when the event is cancelled.

### Observed/Actual behavior

When cancelling PlayerInteractEvent, a linked compass is still added to the player's inventory when right-clicking a lodestone with a compass.

### Steps/models to reproduce

- Make a small plugin which cancels PlayerInteractEvent

```java
public class TestEvent {
    public void onPlayerInteract(PlayerInteractEvent event) {
        System.out.prinlnt("Interact event cancelled");
        event.setCancelled = true;
    } 
}
```
 
- Create a server with this plugin
- Set a block to a lodestone, add a compass to your inventory
- Right-click the lodestone with the compass

### Plugin and Datapack List

Plugins:
- Waystones (discovered during development of this)

Datapacks:

Nothing beyond the built-in datapacks

### Paper version

```
This server is running Paper version 1.21.8-28-main@abf6b6c (2025-08-08T16:40:23Z) (Implementing API version 1.21.8-R0.1-SNAPSHOT)
You are running the latest version
Previous version: 1.21.4-232-12d8fe0 (MC: 1.21.4)
```

### Other

The expected behavior was previously observed to work on version 1.21.4 at least. I noticed this behavior show up after updating to 1.21.8, but after more checking, it appears that it started occurring in version 1.21.7 onward. Versions 1.21.5 and 1.21.6 do not appear to exhibit the behavior observed in later versions.

### LINKED ISSUE #13253: Item desync when using PlayerItemConsumeEvent#setReplacement with same ItemStack
### Expected behavior

Setting a replacement item — even if it’s visually the same item — should result in the slot staying in sync between client and server, just as in vanilla or older Paper builds.

### Observed/Actual behavior

The server correctly keeps the replacement item,
but the client removes it from the hotbar slot.
Re-opening the inventory or relogging shows the item again.

When using PlayerItemConsumeEvent#setReplacement(...) to restore or keep the consumed item,
the client and server can fall out of sync — the client thinks the item was consumed (slot visually empty),
while the server still keeps the item.

This happens even if the replacement is a cloned ItemStack with identical data and amount.
The only way to prevent the desync is to manually resend the slot or call updateInventory().
Before recent Paper changes (possibly around the “sendAllDataToRemote” adjustments),
this behavior did not occur.

### Steps/models to reproduce

```
@Override
public void onEnable() {
    Bukkit.getPluginManager().registerEvents(this, this);
}

@EventHandler
public void onConsume(PlayerItemConsumeEvent event) {
    ItemStack item = event.getItem().clone();
    if (!item.getType().equals(Material.COOKED_BEEF)) return;
    event.setReplacement(item);
}

```

**1. Hold a stack of cooked beef
2. Eat one
3. After eating, the item disappears visually
4. Re-login → item reappears (desync fixed client-side)**

- Happens in 1.21.x (tested on Paper 1.21.8–1.21.10 builds)
- Cloning or reusing the same ItemStack instance both trigger the issue
- Calling updateInventory() or manually sending a SET_SLOT packet resolves the desync
- Possibly related to internal optimizations reducing unnecessary item copies

### Plugin and Datapack List

only the test plugin shown above

### Paper version

[12:40:41 INFO]: This server is running Paper version 1.21.8-60-main@29c8822 (2025-09-06T21:49:13Z) (Implementing API version 1.21.8-R0.1-SNAPSHOT)

### Other

_No response_

### PR DESCRIPTION
**Pull request by Emilxyz**
Fixes to a9399451481e3f8b376484e63909ff6c274f03db that caused inventory desyncs when the client predicted an interaction would result in an item being added to its inventory

Fixes #12947 Fixes #12954 Fixes #13253

### CODE REVIEW

**Comment by Warriorrrr** [comment]
I think Kenny said he was working on some fixes for issues related to this but still had to test them

File: paper-server/patches/sources/net/minecraft/server/network/ServerGamePacketListenerImpl.java.patch [hunk 1]
```diff
@@ -1261,7 +1261,7 @@
                                      this.player.swing(hand, true);
                                  }
 -                            }
-+                            } else { this.player.containerMenu.forceHeldSlot(hand); } // Paper - Fix inventory desync; MC-99075
++                            } else { this.player.containerMenu.sendAllDataToRemote(); } // Paper - Fix inventory desync; MC-99075
```
Comment (kennytv) [inline paper-server/patches/sources/net/minecraft/server/network/ServerGamePacketListenerImpl.java.patch]: Only call this for the spawn protection cases

File: paper-server/patches/sources/net/minecraft/server/level/ServerPlayerGameMode.java.patch [hunk 2]
```diff
@@ -357,7 +357,7 @@
 +            } else if (blockState.is(net.minecraft.world.level.block.Blocks.JIGSAW) || blockState.is(net.minecraft.world.level.block.Blocks.STRUCTURE_BLOCK) || blockState.getBlock() instanceof net.minecraft.world.level.block.CommandBlock) {
 +                player.connection.send(new net.minecraft.network.protocol.game.ClientboundContainerClosePacket(this.player.containerMenu.containerId));
 +            }
-+            player.containerMenu.forceHeldSlot(hand); // SPIGOT-2867
++            this.player.containerMenu.sendAllDataToRemote(); // SPIGOT-2867
```
Comment (kennytv) [inline paper-server/patches/sources/net/minecraft/server/level/ServerPlayerGameMode.java.patch]: _Ideally_ only call this for specific blocks, else keep it at only the held slot. In general keeping track of what blocks actually need this (even if you ignore the specific item interactions) will make sure we dont have to keep guessing which actually cause issues and need to be looked at in other places too

**Review by kennytv — CHANGES_REQUESTED** [review]

**Comment by Emilxyz** [comment]
Okay so I've added a `clientPredictsInteraction` method to keep track of which block & item interactions actually need this. I couldn't really find a good place to put it, so I just slapped it into MCUtil for now. Maybe this should go in its own util class, something like `ClientPredictions`? idk

I scrolled through the creative inventory and tested some blocks that looked like they might be affected by this, but I didn't find anything else. So if anyone knows of any I missed, please let me know.

I added a check to this method on both interact & spawn protection to send the correct update, but I'm a bit confused by
> Only call this for the spawn protection cases

Isn't that what's already being done? Should I split this if check up into something like
```java
if (awaitingPositionFromClient == null) {
  if (!mayInteract && !...) {
    send correct update
    return;
  }
  rest of the code
}
```
image

**Comment by kennytv** [comment]
It's fine in there, looks good; cake plus candle would also be one I think. for the spawn prot one it should just be 
```java
} else if (spawnprot && clientPredictsInteraction) {
    sendAllDataToRemote()
}
```
the other cases should be ignored

**Comment by Emilxyz** [comment]
Implemented the spawn prot thing.

From my testing and understanding you can only place a candle on a cake and not remove it, unless you eat or destroy the cake (but this drops the candle on the ground). I did find something else tho: picking up fluids or honey from a bee hive/nest using a bucket or glass bottle with a count > 1. 
I found no good way to get the fluid they're interacting with that early in the interact, other than using Level#clip. but calling that an extra time per interaction just for this seemed unnecessary. So I decided to just check if they're holding a bucket/glass bottle with a count > 1. That conveniently also covers the bee nest.

<details>
<summary>Screenshot from my test world, with other stuff I tested</summary>
image
</details>

**Comment by Lulu13022002** [comment]
You can't really rely on tags, since datapacks may remove/change their content and you still need to resend held item within the spawn protection when clientPredictsInteraction = false

**Comment by Emilxyz** [comment]
right.. datapacks.. using the tag just would've been too simple. yanked all the blocks that are added to the tag in vanilla and put them in a Set.

added back sending the held item in spawn prot

**Review by kennytv — DISMISSED** [review]

File: paper-server/patches/sources/net/minecraft/server/level/ServerPlayerGameMode.java.patch [hunk 3]
```diff
@@ -357,7 +357,11 @@
 +            } else if (blockState.is(net.minecraft.world.level.block.Blocks.JIGSAW) || blockState.is(net.minecraft.world.level.block.Blocks.STRUCTURE_BLOCK) || blockState.getBlock() instanceof net.minecraft.world.level.block.CommandBlock) {
 +                player.connection.send(new net.minecraft.network.protocol.game.ClientboundContainerClosePacket(this.player.containerMenu.containerId));
 +            }
-+            player.containerMenu.forceHeldSlot(hand); // SPIGOT-2867
++            // Paper start - Fix inventory desync; SPIGOT-2867
++            if (io.papermc.paper.util.MCUtil.clientPredictsInteraction(blockState, stack)) {
++                this.player.containerMenu.sendAllDataToRemote();
++            } else { this.player.containerMenu.forceHeldSlot(hand); }
```
Comment (Lulu13022002) [inline paper-server/patches/sources/net/minecraft/server/level/ServerPlayerGameMode.java.patch]: Can format that statement properly, same below.

File: paper-server/src/main/java/io/papermc/paper/util/MCUtil.java [hunk 4]
```diff
@@ -216,4 +223,24 @@ public static <A, M, C extends Collection<M>> void addAndConvert(final C target,
             target.add(converter.apply(value));
         }
     }
+
+    private static final Set<Block> FLOWER_POTS_WITH_CONTENT = ImmutableSet.of(
```
Comment (Lulu13022002) [inline paper-server/src/main/java/io/papermc/paper/util/MCUtil.java]: Why not check if the block is an instance of FlowerPotBlock and exclude the empty flower pot like you did before?
Actually might even be better to check the content of the flower pot with FlowerPotBlock#getPotted

File: paper-server/src/main/java/io/papermc/paper/util/MCUtil.java [hunk 5]
```diff
@@ -216,4 +223,24 @@ public static <A, M, C extends Collection<M>> void addAndConvert(final C target,
...
+        Blocks.POTTED_BROWN_MUSHROOM, Blocks.POTTED_DEAD_BUSH, Blocks.POTTED_FERN, Blocks.POTTED_CACTUS, Blocks.POTTED_CORNFLOWER,
+        Blocks.POTTED_LILY_OF_THE_VALLEY, Blocks.POTTED_WITHER_ROSE, Blocks.POTTED_BAMBOO, Blocks.POTTED_CRIMSON_FUNGUS,
+        Blocks.POTTED_WARPED_FUNGUS, Blocks.POTTED_CRIMSON_ROOTS, Blocks.POTTED_WARPED_ROOTS, Blocks.POTTED_AZALEA,
+        Blocks.POTTED_FLOWERING_AZALEA, Blocks.POTTED_MANGROVE_PROPAGULE, Blocks.POTTED_CHERRY_SAPLING, Blocks.POTTED_TORCHFLOWER
+    );
+
+    // The client predicts that certain interactions will result in an item being added to its inventory.
+    // If one of these interactions is cancelled, we need to send a full inventory update to prevent desyncs.
+    public static boolean clientPredictsInteraction(final BlockState block, final ItemStack item) {
+        return (FLOWER_POTS_WITH_CONTENT.contains(block.getBlock()))
```
Comment (Lulu13022002) [inline paper-server/src/main/java/io/papermc/paper/util/MCUtil.java]: naming is a bit weird here, maybe state, stack for the parameters?

**Review by Lulu13022002 — COMMENTED** [review]
Seems cancelling the PlayerBucketEntityEvent in creative (or with some custom water bucket with a max stack size >1) doesn't update the right slot too so make sure to test all the other place.

**Comment by Emilxyz** [comment]
I'm honestly not sure anymore what I was cooking there with the set. My thought process must've been something like "I can't check if it's in the tag, but I can check if it's in a set" without thinking further about it. This is much better. Also applied your other suggestions.

I haven't looked into the PlayerBucketEntityEvent yet, but changing the max stack size of items is something I have not considered at all yet, so there is probably more there even (I'm thinking emptying buckets with a count > 1). I'll do some more testing and check other places where the commit changed stuff.

**Comment by Emilxyz** [comment]
I went through all the changes of the commit and tested [a lot of different events](https://gist.github.com/Emilxyz/980fdb95b72e0de23f1036b4f1acf994) here is what I now changed:
- Sending a full update in Bucketable if the player is in creative or holding a stacked bucket, to fix what Lulu has mentioned. When looking into this I also checked out the PlayerInteractEntityEvent, where I found that it was always sending a full inventory update. So I changed that to follow the same logic as in Bucketable.
- Applied the same logic as in `ServerGamePacketListnerImpl#useItemOn` to `ServerGamePacketListenerImpl#useItem`. This would desync when for example picking up a fluid without looking at a block
- Checking if the held item is instance of BucketItem in `MCUtil#clientPredictsInteraction` to fix cancelling stacked water/lava bucket interaction

All other changes seem to behave correctly and I couldn't find anymore edge cases when testing and looking. If anyone can think of anything else I missed please let me know.

EDIT: found something else: milking a cow in creative, or with a stacked bucket, with a cancelled PlayerInteractEntityEvent
EDIT2: okay also mooshroom cows & bowls

**Comment by Emilxyz** [comment]
Maybe this time I won't think of 5 more things the instant I click ready for review. More changes:
- Added a case for cancelling converting mud, either though PlayerInteractEvent or EntityChangeBlockEvent
- Added a separate clientPredictsInteraction method for entity interactions
    - Milking AbstractCow
    - Getting soup from MushroomCow
    - Bucketing Bucketables
- Refactored the clientPredictsInteraction method into multiple if statements, instead of just one big one, to improve readability. Also checking for creative mode now in places where it was previously only item count > 1

**Comment by Lulu13022002** [comment]
Can you look at the InventoryDragEvent, i believe the above commit broke the ability for plugins to set the cursor on the event when the carried item was empty (which might happens at the end of the action when all the items have been placed).

Specifically, this comment is not really accurate: https://github.com/PaperMC/Paper/blob/main/paper-server/patches/sources/net/minecraft/world/inventory/AbstractContainerMenu.java.patch#L152

**Comment by Emilxyz** [comment]
You were right, this broke setting the carried item when it's empty. I'm not sure what behavior was even fixed with that if statement, I did some testing by just removing it and everything seemed to work as expected when the inventory is closed server side. To me it doesn't look like getCarried can return null anyways so this is basically what was done before the commit.

https://github.com/user-attachments/assets/c7e34756-f29a-4aa3-bca5-62dfcd18d8b4

In the first test I kept holding mouse one not letting the event fire and it dropped the old item stack. The second test I release mouse 1 and the event changes my carried item to a diamond sword and that is dropped when the inventory is closed. Am I missing something obvious here?

**Comment by AtriusX** [comment]
Has there been any movement on this? Checked on the latest build of 1.21.8 as of writing (build 60), and the underlying issue still seems to be present.

**Comment by kennytv** [comment]
I'll check on this soon

**Comment by Lulu13022002** [comment]
If you want to handle https://github.com/PaperMC/Paper/issues/13253 since it's still the same commit.

**Comment by Emilxyz** [comment]
Yeah I'll take a look this weekend

**Comment by Emilxyz** [comment]
I included a fix for setting the replacement item in the consume event, but I haven't had time to fully look into the bucket events also mentioned in that issue. So far I believe that it might be related to https://github.com/PaperMC/Paper/commit/a9399451481e3f8b376484e63909ff6c274f03db#diff-041b13ef604c2316fbe5d887eea7c155cedf23bdfccd031a839f75a8c8384bbaR315, but I will look into it further when I find more time

**Comment by Emilxyz** [comment]
That took a bit, sorry about that. I finally found time to look into the bucket events and the diff I suspected was indeed the cause to the issue. It is now changed to behave like the other places

**Comment by kennytv** [comment]
Could you rebase the PR?

File: paper-server/patches/sources/net/minecraft/server/network/ServerGamePacketListenerImpl.java.patch [hunk 6]
```diff
@@ -1239,26 +1239,34 @@
...
                                      this.player.sendSystemMessage(component, true);
                                  } else if (interactionResult instanceof InteractionResult.Success success
 -                                    && success.swingSource() == InteractionResult.SwingSource.SERVER) {
 +                                    && success.swingSource() == InteractionResult.SwingSource.SERVER && !this.player.gameMode.interactResult) { // Paper - Call interact event
                                      this.player.swing(hand, true);
                                  }
--                            }
-+                            } else { this.player.containerMenu.forceHeldSlot(hand); } // Paper - Fix inventory desync; MC-99075
++                            // Paper start - Fix inventory desync; MC-99075
++                            } else if (!mayInteract) {
```
Comment (kennytv) [inline paper-server/patches/sources/net/minecraft/server/network/ServerGamePacketListenerImpl.java.patch]: See my first reviews still, should only cover spawn protection specifically, or was there another case this was intentionally targeting?

File: paper-server/patches/sources/net/minecraft/server/level/ServerPlayerGameMode.java.patch [hunk 7]
```diff
@@ -308,16 +308,25 @@
...
+             InteractionResult interactionResult = stack.use(level, player, hand);
+             ItemStack itemStack;
+             if (interactionResult instanceof InteractionResult.Success success) {
+@@ -321,7 +_,9 @@
                  }
  
                  if (!player.isUsingItem()) {
--                    player.inventoryMenu.sendAllDataToRemote();
-+                    player.inventoryMenu.broadcastChanges(); // Paper - change to broadcastChanges, super old code that might not even be needed at all
++                    if (io.papermc.paper.util.MCUtil.clientPredictsInteraction(player, net.minecraft.world.level.block.Blocks.AIR.defaultBlockState(), stackBeforeUse)) // Paper - Optimize sendAllDataToRemote calls
```
Comment (kennytv) [inline paper-server/patches/sources/net/minecraft/server/level/ServerPlayerGameMode.java.patch]: Is it possible to move the sync checks to the specific events instead? This place is a bit too generic (and presumably part of a buggy codepath) and currently still results in a desync with
```java
    @EventHandler
    public void on(PlayerBucketFillEvent event) {
        event.setItemStack(ItemStack.of(event.getBucket()));
    }
```

**Review by kennytv — CHANGES_REQUESTED** [review]
The rest looks good, thanks for going into such detail with the different code points

**Review by kennytv — APPROVED** [review]
The empty/fill events can be addressed later
