### PR TITLE
Fix drop skulls by Powered Creeper

### LINKED ISSUE #13164: Charged creeper explosions no longer drop skulls of other mobs
### Expected behavior

Killing a zombie with a charged creeper explosion causes a zombie skull to drop in addition to the rotten flesh.

### Observed/Actual behavior

only the rotten flesh is dropped, but not the skull

### Steps/models to reproduce

- build a bedrock hole
- spawn a creeper
- summon a lighting bolt via command
- spawn a zombie
- right-click the creeper with a flint and steel, causing an explosion

### Plugin and Datapack List

no plugins.

There are 3 data pack(s) enabled: [vanilla (built-in)], [file/bukkit (world)], [paper (built-in)]

### Paper version

[20:45:29 INFO]: Checking version, please wait...
[20:45:29 INFO]: This server is running Paper version 1.21.10-64-main@fba780d (2025-10-07T18:34:29Z) (Implementing API version 1.21.10-R0.1-SNAPSHOT)
You are running the latest version

### Other

works in vanilla (using the vanilla jar in the paper cache).

according to @Lulu13022002 :
> that might be caused by that forceDrops flag seems the skull is dropped past the death event

https://discord.com/channels/289587909051416579/289587909051416579/1426268449633603777

### PR DESCRIPTION
**Pull request by Doc94**
Closes https://github.com/PaperMC/Paper/issues/13164
Also fix a strange double call in Entity...

### CODE REVIEW

File: paper-server/patches/sources/net/minecraft/world/entity/LivingEntity.java.patch [hunk 1]
```diff
@@ -811,6 +811,9 @@
 -                if (entity == null || entity.killedEntity(serverLevel, this, damageSource)) {
 +                // Paper - move below into if for onKill
 +                // Paper start
++                if (entity instanceof net.minecraft.world.entity.monster.Creeper creeper) { // Creeper has logic for drops we need capture
```
Comment (Doc94) [inline paper-server/patches/sources/net/minecraft/world/entity/LivingEntity.java.patch:814]: I prefer make a copy an call for creeper cases because that method has a field for know if a skull was already added then not make issues if its called again later of EntityDeathEvent

Comment (electronicboy) [reply paper-server/patches/sources/net/minecraft/world/entity/LivingEntity.java.patch:814]: Why just creepers?

Comment (Doc94) [reply paper-server/patches/sources/net/minecraft/world/entity/LivingEntity.java.patch:814]: The issue is with creepers the other class using this method is Zombie and has logic for "spawn another" then call this before the death event (what can be cancel) i think can cause a mess in that...

Comment (electronicboy) [reply paper-server/patches/sources/net/minecraft/world/entity/LivingEntity.java.patch:814]: Yea, just noticed that all of the others have logic you don't want to run if their death is cancelled, that's a pain

Comment (electronicboy) [reply paper-server/patches/sources/net/minecraft/world/entity/LivingEntity.java.patch:814]: Well, same situation here though, we would need to revert state if the death is cancelled? at least here it's manageable I guess

Comment (Doc94) [reply paper-server/patches/sources/net/minecraft/world/entity/LivingEntity.java.patch:814]: > Well, same situation here though, we would need to revert state if the death is cancelled? at least here it's manageable I guess

what need revert in this case? the creeper is still removed by the explosion then not need revert the drop field unless i miss something?

Comment (electronicboy) [reply paper-server/patches/sources/net/minecraft/world/entity/LivingEntity.java.patch:814]: Is the death event cancellable? If the death is cancelled, the boolean should be restored, as its drops won't occur? Even if other behaviour dictates that this isn't needed, we should be considering this (and maybe putting this area of code into our "this really needs to be looked into" list)

Comment (Doc94) [reply paper-server/patches/sources/net/minecraft/world/entity/LivingEntity.java.patch:814]: Okay the only case where i find valid restore the flag is the creeper explode with many mobs arround if cancel one the other need run check dropSkull logic then i add this..
not like the solution for check creeper and manage but other solutions require make more changes :/

**Review by electronicboy — APPROVED** [review]
This is in the "far from ideal, but if we want a proper fix for this, this will require behavioural changes/much more work"

**Review by Warriorrrr — APPROVED** [review]
