### PR TITLE
Do not blow up accessing unregistered memories from API (Fixes #12618)

### LINKED ISSUE #12618: LivingEntity#getMemory throws IllegalStateException if the memory isn't registered for said entity.
### Expected behavior

As per the javadocs, when retrieving an unregistered memory, it should return null.
Image

### Observed/Actual behavior

When getting an unregistered Memory from an entity (said entity doesn't have that memory module), IllegalStateException is throw.

I have an addon for Skript, and someone just reported this to me.

Image
See issue on my plugin here https://github.com/ShaneBeee/SkBee/issues/803 for more info.

### Steps/models to reproduce

Simple code to test:
```java
Location memory = somePigEntity.getMemory(MemoryKey.JOB_SITE);
```

### Plugin and Datapack List

```
[17:38:57 INFO]: ℹ Server Plugins (9):
[17:38:57 INFO]: Paper Plugins (1):
[17:38:57 INFO]:  - CorePlugin
[17:38:57 INFO]: Bukkit Plugins (8):
[17:38:57 INFO]:  - BeerPlugin, PermissionsEx, SkBee, SkBriggy, SkNMS, Skript, skript-reflect, StressTestBots
> 
```

### Paper version

This server is running Paper version 1.21.5-103-main@2ba1675 (2025-05-29T12:14:46Z) (Implementing API version 1.21.5-R0.1-SNAPSHOT)

### Other

I dont think this error happened before, but I think Mojang has started using `Optional` in more places.
This is from NMS Brain:
Image

### PR DESCRIPTION
**Pull request by electronicboy**

### CODE REVIEW

File: paper-server/src/main/java/org/bukkit/craftbukkit/entity/CraftLivingEntity.java [hunk 1]
```diff
@@ -905,7 +906,8 @@ public Set<UUID> getCollidableExemptions() {
 
     @Override
     public <T> T getMemory(MemoryKey<T> memoryKey) {
-        return (T) this.getHandle().getBrain().getMemory(CraftMemoryKey.bukkitToMinecraft(memoryKey)).map(CraftMemoryMapper::fromNms).orElse(null);
+        final Optional<?> memory = this.getHandle().getBrain().getMemoryInternal(CraftMemoryKey.bukkitToMinecraft(memoryKey));
+        return memory != null ? (T) memory.map(CraftMemoryMapper::fromNms).orElse(null) : null;
```
Comment (yannicklamprecht) [inline paper-server/src/main/java/org/bukkit/craftbukkit/entity/CraftLivingEntity.java:910]: memory is an optional, so I expect it to never be null or did you find a case where null instead of an instance of optional is returned?

Comment (electronicboy) [reply paper-server/src/main/java/org/bukkit/craftbukkit/entity/CraftLivingEntity.java:910]: image
Yes

**Review by Machine-Maker — APPROVED** [review]

**Review by Owen1212055 — APPROVED** [review]

File: paper-server/src/main/java/org/bukkit/craftbukkit/entity/CraftLivingEntity.java (hunk 1 above)
Comment (justADeni) [reply paper-server/src/main/java/org/bukkit/craftbukkit/entity/CraftLivingEntity.java:910]: This is so dumb. What's the point of using Optionals if the Optional ref. can be null, Mojang?
