### PR TITLE
fix: only fire dragon shoot level event on successful event

### LINKED ISSUE #12976: EnderDragon still plays Fireball shoot Sound even when EnderDragonShootFireballEvent is canceled
### Expected behavior

When I cancel EnderDragonShootFireballEvent I would expect to not hear the sound the dragon makes when shooting a Fireball.

### Observed/Actual behavior

The Fireball is not shot, but the sound plays.

### Steps/models to reproduce

Just cancel the EnderDragonShootFireballEvent event.

### Plugin and Datapack List

Tested with only my own plugin which only had that event canceled. No Datapacks other than the default ones (bukkit, paper, vanilla)

### Paper version

This server is running Paper version 1.21.8-31-main@86b716b (2025-08-13T15:40:19Z) (Implementing API version 1.21.8-R0.1-SNAPSHOT)
You are running the latest version
Previous version: 1.21.8-30-4fe66e5 (MC: 1.21.8)

### Other

Not sure if this is something that paper can fix.. Would be cool though.

### PR DESCRIPTION
**Pull request by Emilxyz**
only fires the "Ender dragon shoots" (1017) level event if the `EnderDragonShootFireballEvent` is not cancelled.

Fixes #12976

### CODE REVIEW

File: paper-server/patches/sources/net/minecraft/world/entity/boss/enderdragon/phases/DragonStrafePlayerPhase.java.patch [hunk 1]
```diff
@@ -1,14 +1,21 @@
...
+                             level.levelEvent(null, 1017, this.dragon.blockPosition(), 0);
                          }
  
                          DragonFireball dragonFireball = new DragonFireball(level, this.dragon, vec32.normalize());
 +                        dragonFireball.preserveMotion = true; // Paper - Fix Entity Teleportation and cancel velocity if teleported
                          dragonFireball.snapTo(d2, d3, d4, 0.0F, 0.0F);
-+                        if (new com.destroystokyo.paper.event.entity.EnderDragonShootFireballEvent((org.bukkit.entity.EnderDragon) this.dragon.getBukkitEntity(), (org.bukkit.entity.DragonFireball) dragonFireball.getBukkitEntity()).callEvent()) // Paper - EnderDragon Events
++                        if (new com.destroystokyo.paper.event.entity.EnderDragonShootFireballEvent((org.bukkit.entity.EnderDragon) this.dragon.getBukkitEntity(), (org.bukkit.entity.DragonFireball) dragonFireball.getBukkitEntity()).callEvent()) { // Paper - EnderDragon Events
++                            if (!this.dragon.isSilent()) level.levelEvent(null, 1017, this.dragon.blockPosition(), 0); // Paper - EnderDragon Events; Fire after shoot fireball event
```
Comment (Lulu13022002) [inline paper-server/patches/sources/net/minecraft/world/entity/boss/enderdragon/phases/DragonStrafePlayerPhase.java.patch]: You can use the constant from LevelEvent, so if that number ever change it's still relevant

Comment (Emilxyz) [reply paper-server/patches/sources/net/minecraft/world/entity/boss/enderdragon/phases/DragonStrafePlayerPhase.java.patch]: good to know, thanks!

**Review by electronicboy — APPROVED** [review]

**Review by notTamion — APPROVED** [review]
