### PR TITLE
Fix option fixClimbingBypassCramming

### LINKED ISSUE #12748: Entities Collide with fix-climbing-bypassing-cramming-rule Enabled
## Expected behavior
When the `fix-climbing-bypassing-cramming-rule: true` option is enabled, entities should not collide with each other, similar to vanilla Minecraft behavior. The cramming rule should still function to kill entities when there are too many in a confined space, without causing collision issues.

Image
_Entities should not collide, like in vanilla, with cramming rule killing excess entities instead._

Image
_Entities in scaffolds collide and push each other with fix-climbing-bypassing-cramming-rule: true enabled._

## Observed/Actual behavior
With `fix-climbing-bypassing-cramming-rule: true` enabled, entities now collide with each other, which is not the intended behavior. This collision should not occur, as it deviates from vanilla mechanics where entities do not collide under these conditions.

## Steps/models to reproduce
1. Set up a PaperMC server with the latest version.
2. Enable `fix-climbing-bypassing-cramming-rule: true` in the configuration.
3. Place multiple entities (e.g., animals or mobs) within a confined space, such as the structure shown in the image (allays in scaffold).
4. Observe that entities collide with each other instead of passing through or being killed by the cramming rule without collision.

## Plugin and Datapack List
- No additional plugins or datapacks are used that affect entity collision or cramming rules.

# Paper version
```
[19:45:35] [ServerMain/INFO]: [bootstrap] Loading Paper 1.21.4-232-ver/1.21.4@12d8fe0 (2025-06-09T10:15:42Z) for Minecraft 1.21.4
```

## Other
- The issue is observed in a custom structure designed to test entity cramming, as depicted in the provided image.
- The collision behavior was tested with multiple entity types (e.g., chickens, allays) and consistently resulted in unwanted collisions.
- This behavior disrupts gameplay mechanics that rely on vanilla cramming rules without entity collisions.

### PR DESCRIPTION
**Pull request by HaHaWTH**
This pull request fixes config option `fixClimbingBypassingCrammingRule` not working on Paper 1.21.7, the config value is never getting passed.

I directly edited the `Level#getPushableEntities` as the only usage is the one in `LivingEntity#pushEntities`.

### CODE REVIEW

**Comment by Phoenix616** [comment]
It's passed [here](https://github.com/PaperMC/Paper/blob/main/paper-server/patches/sources/net/minecraft/world/entity/LivingEntity.java.patch#L1603) to `LivingEntity#isPushable` which as far as I can tell should be enough. Are you saying that how cramming itself works changed so that this `isPushable` check isn't responsible for the cramming damage anymore?

**Comment by HaHaWTH** [comment]
> It's passed [here](https://github.com/PaperMC/Paper/blob/main/paper-server/patches/sources/net/minecraft/world/entity/LivingEntity.java.patch#L1603) to `LivingEntity#isPushable` which as far as I can tell should be enough. Are you saying that how cramming itself works changed so that this `isPushable` check isn't responsible for the cramming damage anymore?

The `getPushableEntities` is using `EntitySelector.pushableBy`, which is always passing a `false` to isCollidable
IMG

The isPushable check at head passed but getting entities ignored this, so the result entity list won't include climbing entities even `fixClimbingBypassingCrammingRule` is true

**Comment by Phoenix616** [comment]
Right, looks like there is an unnecessary change there in the `pushableBy` method:

There should be no reason to even have a `pushableBy(Entity, boolean)` method with the `ignoreClimbing` parameter (as it is never set to anything but `false`) and it should work when simply using the same code as before the patch (at least for the push-check) which used `isPushable` (which then uses the config option) instead of the custom `isCollidable` which takes the parameter.

I personally think that's the cleaner approach as it actually reduces the diff instead of increasing it as your solution does.

**Comment by HaHaWTH** [comment]
> Right, looks like there is an unnecessary change there in the `pushableBy` method:
> 
> There should be no reason to even have a `pushableBy(Entity, boolean)` method with the `ignoreClimbing` parameter (as it is never set to anything but `false`) and it should work when simply using the same code as before the patch (at least for the push-check) which used `isPushable` (which then uses the config option) instead of the custom `isCollidable` which takes the parameter.
> 
> I personally think that's the cleaner approach as it actually reduces the diff instead of increasing it as your solution does.

Yeah but, vanilla uses `pushableBy` entity selector, the pushable added by Paper is a redirection, which prevents diffs from flying everywhere. And some entities don't need this check like boats and minecarts. (see AbstractBoat and Old/NewMinecartBehavior)

**Comment by Phoenix616** [comment]
I'm unsure what you mean by "prevents diffs from flying everywhere" seeing as you are increasing the diff which would be my understanding of "flying everyhwere".

Also Boats and Minecarts are not a LivingEntity hence why the climbing setting wouldn't even apply to them (it's defined in [`LivingEntity#isPushable`](https://github.com/PaperMC/Paper/blob/main/paper-server/patches/sources/net/minecraft/world/entity/LivingEntity.java.patch#L1603) after all)

**Comment by Phoenix616** [comment]
Just to be a bit more clear, this is what I suggest (I haven't tested that though)
image

**Comment by HaHaWTH** [comment]
Yea that would make sense, i assume that should be included in another PR? Seems kinda off-topic for this one though( ´▽` )

**Comment by Phoenix616** [comment]
> Yea that would make sense, i assume that should be included in another PR? Seems kinda off-topic for this one though( ´▽` )

What do you mean? It's literally the solution for the issue this PR solves but simpler.

**Comment by HaHaWTH** [comment]
> > Yea that would make sense, i assume that should be included in another PR? Seems kinda off-topic for this one though( ´▽` )
> 
> What do you mean? It's literally the solution for the issue this PR solves but simpler.

Ah I see, what I thought before is to minimize diffs made by this PR, sry for my misunderstanding

File: paper-server/patches/sources/net/minecraft/world/entity/EntitySelector.java.patch [hunk 1]
```diff
@@ -23,31 +23,49 @@
  
      private EntitySelector() {
      }
-@@ -27,18 +_,24 @@
+@@ -27,29 +_,31 @@
      }
  
      public static Predicate<Entity> pushableBy(Entity entity) {
 +        // Paper start - Climbing should not bypass cramming gamerule
```
Comment (Phoenix616) [inline paper-server/patches/sources/net/minecraft/world/entity/EntitySelector.java.patch]: Comment is not necessary, this method is not touched for the climbing cramming bypass option

File: paper-server/patches/sources/net/minecraft/world/entity/EntitySelector.java.patch [hunk 2]
```diff
@@ -23,31 +23,49 @@
...
          Team.CollisionRule collisionRule = team == null ? Team.CollisionRule.ALWAYS : team.getCollisionRule();
          return (Predicate<Entity>)(collisionRule == Team.CollisionRule.NEVER
              ? Predicates.alwaysFalse()
              : NO_SPECTATORS.and(
 -                entity1 -> {
 -                    if (!entity1.isPushable()) {
-+                entity1 -> { final Entity pushedEntity = entity1; // Paper - OBFHELPER
-+                    if (!pushedEntity.isCollidable(ignoreClimbing) || !pushedEntity.canCollideWithBukkit(entity) || !entity.canCollideWithBukkit(pushedEntity)) { // CraftBukkit - collidable API // Paper - Climbing should not bypass cramming gamerule
++            entity1 -> { final Entity pushedEntity = entity1; // Paper - OBFHELPER
++                if (!pushedEntity.isPushable() || !pushedEntity.canCollideWithBukkit(entity) || !entity.canCollideWithBukkit(pushedEntity)) { // CraftBukkit - collidable API // Paper - Climbing should not bypass cramming gamerule
```
Comment (Phoenix616) [inline paper-server/patches/sources/net/minecraft/world/entity/EntitySelector.java.patch]: Comment is not necessary, this line is not touched for the climbing cramming bypass option (as `pushedEntity#isPushable` is the Vanilla code and the other change is just the collidable API)

File: paper-server/patches/sources/net/minecraft/world/entity/EntitySelector.java.patch [hunk 3]
```diff
@@ -23,31 +23,49 @@
...
++                        return (collisionRule != Team.CollisionRule.PUSH_OWN_TEAM && collisionRule1 != Team.CollisionRule.PUSH_OWN_TEAM || !flag)
++                            && (collisionRule != Team.CollisionRule.PUSH_OTHER_TEAMS && collisionRule1 != Team.CollisionRule.PUSH_OTHER_TEAMS || flag);
+                     }
++                } else {
++                    return false;
+                 }
+-            ));
++            }
++        ));
++        // Paper end - Climbing should not bypass cramming gamerule
```
Comment (Phoenix616) [inline paper-server/patches/sources/net/minecraft/world/entity/EntitySelector.java.patch]: Comment is not necessary, this method is not touched for the climbing cramming bypass option

**Review by Phoenix616 — COMMENTED** [review]
That's how I meant it, yea. Just that there are now some left-over comments regarding the climbing option which shouldn't really be necessary as that feature does not touch this method anymore.

**Comment by HaHaWTH** [comment]
> That's how I meant it, yea. Just that there are now some left-over comments regarding the climbing option which shouldn't really be necessary as that feature does not touch this method anymore.

Done.

**Review by diegogarciarojo — APPROVED** [review]

**Review by electronicboy — APPROVED** [review]

**Comment by MC-XiaoHei** [comment]
Hello, is there any plan to merge this PR? I saw that it has been approved, but there has been no news for three weeks.

**Review by Warriorrrr — APPROVED** [review]
