### PR TITLE
OldEnum#valueOf check for valid NamespacedKey

### LINKED ISSUE #13594: NPE instead IAE when using Sound.valueOf with invalid sound
### Stack trace

```
Caused by: java.lang.NullPointerException: Cannot invoke "org.bukkit.NamespacedKey.getNamespace()" because "key" is null
        at org.bukkit.craftbukkit.util.CraftNamespacedKey.toMinecraft(CraftNamespacedKey.java:22) ~[paper-1.21.8.jar:1.21.8-60-29c8822]
        at io.papermc.paper.util.MCUtil.toResourceKey(MCUtil.java:199) ~[paper-1.21.8.jar:1.21.8-60-29c8822]
        at org.bukkit.craftbukkit.CraftRegistry.get(CraftRegistry.java:199) ~[paper-1.21.8.jar:1.21.8-60-29c8822]
        at org.bukkit.craftbukkit.CraftRegistry.get(CraftRegistry.java:132) ~[paper-1.21.8.jar:1.21.8-60-29c8822]
        at org.bukkit.craftbukkit.util.CraftMagicNumbers.get(CraftMagicNumbers.java:479) ~[paper-1.21.8.jar:1.21.8-60-29c8822]
        at org.bukkit.Sound.valueOf(Sound.java:3498) ~[paper-api-1.21.8-R0.1-SNAPSHOT.jar:?]
```

### Plugin and Datapack List

BetonQuest

### Actions to reproduce (if known)

Read from user input a sound, like `minecraft:entity.player.levelup99!!!⁩⁩` and use the Sound#valueOf method (from an old api version) with it.

### Paper version

This server is running Paper version 1.21.8-60-main@29c8822 (2025-09-06T21:49:13Z) (Implementing API version 1.21.8-R0.1-SNAPSHOT)
You are running the latest version
Previous version: 1.21.4-221-c467df9 (MC: 1.21.4)

### Other

I catch the IllegalArgumentException I would expect from the `valueOf` method. But the `NamespacedKey#fromString` returns null when it is an invalid key and that is passed to a method where an actual key is expected (see [Sound.java](https://github.com/PaperMC/Paper/blob/main/paper-api/src/main/java/org/bukkit/Sound.java#L3716)).
Checking there for null like at the end of the method would throw the expected Exception instead NPE.
Other OldEnums are "affected" by that too.

### PR DESCRIPTION
**Pull request by Doc94**
This PR fix https://github.com/PaperMC/Paper/issues/13594 where the OldEnum#valueOf (its a reference i know its not like that) can take invalid name like "@" and throw a NPE in the Registry class because the NamespaceKey generated before is null for the invalid characters, the change its just check the NamespaceKey and throw an issue, the only exception its the Sound where another check is made later then just avoid check Registry if the key was invalid

### CODE REVIEW

**Review by electronicboy — APPROVED** [review]

**Comment by Lulu13022002** [comment]
Make sure to catch all the places using NamespacedKey.fromString like Art.getByName, also I think this can just fallback to the latter precondition keep in mind this try to mimic Enum#valueOf.

**Comment by Doc94** [comment]
> Make sure to catch all the places using NamespacedKey.fromString like Art.getByName, also I think this can just fallback to the latter precondition keep in mind this try to mimic Enum#valueOf.

latter precondition?

File: paper-api/src/main/java/org/bukkit/Art.java [hunk 1]
```diff
@@ -231,8 +231,10 @@ static Art getById(int id) {
     @Nullable
     static Art getByName(@NotNull String name) {
         Preconditions.checkArgument(name != null, "Name cannot be null");
+        final NamespacedKey key = NamespacedKey.fromString(name.toLowerCase(Locale.ROOT));
+        Preconditions.checkArgument(key != null, "Invalid name %s", name);
```
Comment (Lulu13022002) [inline paper-api/src/main/java/org/bukkit/Art.java]: That's incorrect the method is nullable for a reason and by latter precondition I meant only throw with the message "No art found with the name" for invalid key in valueOf.

Comment (Doc94) [reply paper-api/src/main/java/org/bukkit/Art.java]: For the getByName then just revert last change and if the namespace its invalid just return null?

and for the last you mean just change the message not? (i use that because well.. copy-paste...)

Comment (Lulu13022002) [reply paper-api/src/main/java/org/bukkit/Art.java]: I did the changes

**Review by Warriorrrr — APPROVED** [review]

**Review by Machine-Maker — APPROVED** [review]
