### PR TITLE
Fix per-world and per-player time

### LINKED ISSUE #13802: Resolve todos around per-world time
- Either the timeCommandAffectsAllWorlds option needs removing, or levels hold their own clock managers
- Add API for world clocks (and possibly timelines)

issue made for separate tracking

### LINKED ISSUE #13808: /time set in other dimensions  not working.
### Expected behavior

When you type /time set day it should set it to day 
or
/time set night should set it to night.

### Observed/Actual behavior

it changes it to that time for a split second then reverts back to before you typed the command.

### Steps/models to reproduce

Use the datapack i linked, go to one of the other worlds and try changing the time.

Yes advance day is active. 
Yes the datapack is set up correctly it works fine in single player.

### Plugin and Datapack List

[09:21:03 INFO]: Slphia issued server command: /plugins
[09:21:10 INFO]: ℹ Server Plugins (0)

[09:21:22 INFO]: There are 3 data pack(s) enabled: [vanilla (built-in)], [paper (built-in)], [file/ghostly (world)]
[09:21:22 INFO]: There are 1 data pack(s) available: [file/bukkit (world)]

### Paper version

This server is running Paper version 26.1.2-18-main@6bac3c9 (2026-04-20T10:18:10Z) (Implementing API version 26.1.2.build.18-alpha)
You are running the latest version
Previous version: 26.1.2-2570-e64b1b2 (MC: 26.1.2)

### Other

[ghostly.zip](https://github.com/user-attachments/files/26925227/ghostly.zip)

### PR DESCRIPTION
**Pull request by kennytv**
Makes clock managers per-world, given clocks have to be put into client-synchronized registries, which is a big no no and unnecessary block for creating worlds on the fly

Splits TimeSkipEvent into a new ClockTimeSkipEvent for when the new config option is toggled to make clocks global again. the actual clock API will be added separately. the time command succeeds even if the event is cancelled (as before?), but that didn't look like something to waste time on

Tested by creating new worlds / switching worlds with per-player time set and/or paused

### CODE REVIEW

File: paper-server/patches/sources/net/minecraft/server/commands/TimeCommand.java.patch [hunk 1]
```diff
@@ -1,67 +1,102 @@
...
 -        clockManager.setTotalTicks(clock, totalTicks);
-+        // clockManager.setTotalTicks(clock, totalTicks);
++        ServerClockManager clockManager = source.getLevel().clockManager();
++        long currentTotalTicks = clockManager.getTotalTicks(clock);
++        org.bukkit.event.world.ClockTimeSkipEvent event = org.bukkit.craftbukkit.event.CraftEventFactory.callTimeSkipEvent(source, totalTicks - currentTotalTicks);
++        if (event.callEvent()) {
++            clockManager.setTotalTicks(clock, currentTotalTicks + event.getSkipAmount());
++        }
          source.sendSuccess(() -> Component.translatable("commands.time.set.absolute", clock.getRegisteredName(), totalTicks), true);
          return totalTicks;
```
Comment (Doc94) [inline paper-server/patches/sources/net/minecraft/server/commands/TimeCommand.java.patch]: The totalTicks needs to be updated for show the player the correct value set if event change that.

File: paper-api/src/main/java/org/bukkit/event/world/ClockTimeSkipEvent.java [hunk 2]
```diff
@@ -0,0 +1,98 @@
...
+import org.jetbrains.annotations.ApiStatus;
+import org.jetbrains.annotations.NotNull;
+
+/**
+ * Called when the time skips for a world clock.
+ * <p>
+ * If the event is cancelled the time will not change.
+ */
+// TODO - snapshot - 26.1 clock
+public class ClockTimeSkipEvent extends Event implements Cancellable {
```
Comment (Doc94) [inline paper-api/src/main/java/org/bukkit/event/world/ClockTimeSkipEvent.java:17]: Maybe include the experimental if in future wanna move something?

PD: Maybe include by the moment a key reference for what clock was used? (vanilla or datapack)

File: paper-api/src/main/java/org/bukkit/event/world/TimeSkipEvent.java [hunk 3]
```diff
@@ -10,60 +9,29 @@
  * Called when the time skips in a world.
  * <p>
  * If the event is cancelled the time will not change.
+ *
+ * @see ClockTimeSkipEvent for changing of clocks that affect all worlds
  */
-// TODO - snapshot - 26.1 API needed for clock!
-public class TimeSkipEvent extends WorldEvent implements Cancellable {
+public class TimeSkipEvent extends ClockTimeSkipEvent {
```
Comment (Owen1212055) [inline paper-api/src/main/java/org/bukkit/event/world/TimeSkipEvent.java:15]: This is a break?

File: paper-server/patches/sources/net/minecraft/server/level/ServerLevel.java.patch [hunk 4]
```diff
@@ -22,6 +22,7 @@
 +    private final WeatherData weatherData;
 +    public final net.minecraft.world.level.timers.TimerQueue<net.minecraft.server.MinecraftServer> scheduledEvents;
 +    public final WorldGenSettings worldGenSettings;
++    private ServerClockManager clockManager;
```
Comment (Doc94) [inline paper-server/patches/sources/net/minecraft/server/level/ServerLevel.java.patch]: missing Nullable annotation?

**Comment by Doc94** [comment]
Clocks items are still broken.

https://github.com/user-attachments/assets/ac4b6ea1-4e37-4141-a30c-41a601ea18a4

this was tested in a new world, the main world the item works.

File: paper-server/patches/sources/net/minecraft/world/clock/ServerClockManager.java.patch [hunk 5]
```diff
@@ -18,36 +48,86 @@
...
-+        return this.getInstance(definition).paused;
+     public ClientboundSetTimePacket createFullSyncPacket() {
+-        return new ClientboundSetTimePacket(this.getGameTime(), Util.mapValues(this.clocks, clock -> clock.packNetworkState(this.server)));
++        // Paper start - per-player time
++        return this.createFullSyncPacket(null);
 +    }
 +
-+    public float partialTick(final Holder<WorldClock> definition) {
-+        return this.getInstance(definition).partialTick;
++    public ClientboundSetTimePacket createFullSyncPacket(final net.minecraft.server.level.ServerPlayer player) {
```
Comment (Doc94) [inline paper-server/patches/sources/net/minecraft/world/clock/ServerClockManager.java.patch:81]: This need to be marked Nullable, same with packNetworkState with the null player

Comment (kennytv) [reply paper-server/patches/sources/net/minecraft/world/clock/ServerClockManager.java.patch:81]: The lines were too long so I skipped it 🛏️

**Comment by kennytv** [comment]
> Clocks items are still broken.
> 
>  2026-04-23_12-08-24.mp4 
> this was tested in a new world, the main world the item works.

They're hardcoded to only work in the overworld level

**Comment by masmc05** [comment]
A resource pack would be needed to make them work in a custom world with a custom item model definition

File: paper-api/src/main/java/org/bukkit/event/world/ClockTimeSkipEvent.java [hunk 6]
```diff
@@ -0,0 +1,99 @@
+package org.bukkit.event.world;
+
+import org.bukkit.event.Cancellable;
+import org.bukkit.event.Event;
+import org.bukkit.event.HandlerList;
+import org.jetbrains.annotations.ApiStatus;
+import org.jetbrains.annotations.NotNull;
```
Comment (Lulu13022002) [inline paper-api/src/main/java/org/bukkit/event/world/ClockTimeSkipEvent.java]: Use jspecify for new classes

File: paper-server/src/main/java/org/bukkit/craftbukkit/event/CraftEventFactory.java [hunk 7]
```diff
@@ -2417,4 +2420,11 @@ public static boolean callPlayerToggleEntityAgeLockEvent(net.minecraft.world.ent
         }
         return true;
     }
+
+    public static ClockTimeSkipEvent callTimeSkipEvent(final CommandSourceStack source, final long skipAmount) {
```
Comment (Lulu13022002) [inline paper-server/src/main/java/org/bukkit/craftbukkit/event/CraftEventFactory.java]: That's a bad name for this method either move some logic here or rename it.

File: paper-server/patches/sources/net/minecraft/world/clock/ServerClockManager.java.patch [hunk 8]
```diff
@@ -1,5 +1,35 @@
...
+ 
+     private ServerClockManager(final PackedClockStates packedClockStates) {
+@@ -37,6 +_,12 @@
+     }
+ 
+     public void init(final MinecraftServer server) {
++        // Paper start - per-world time
++        this.init(server, null);
++    }
++    public void init(final MinecraftServer server, @org.checkerframework.checker.nullness.qual.Nullable final ServerLevel level) {
```
Comment (Lulu13022002) [inline paper-server/patches/sources/net/minecraft/world/clock/ServerClockManager.java.patch]: Use jspecify

File: paper-server/src/main/java/io/papermc/paper/configuration/GlobalConfiguration.java [hunk 9]
```diff
@@ -30,7 +30,7 @@
 @SuppressWarnings({"CanBeFinal", "FieldCanBeLocal", "FieldMayBeFinal", "NotNullFieldNotInitialized", "InnerClassMayBeStatic"})
 public class GlobalConfiguration extends ConfigurationPart {
     private static final Logger LOGGER = LogUtils.getLogger();
-    static final int CURRENT_VERSION = 31; // (when you change the version, change the comment, so it conflicts on rebases): allow-nether property to config
+    static final int CURRENT_VERSION = 32; // (when you change the version, change the comment, so it conflicts on rebases): rename all-worlds time config
```
Comment (Lulu13022002) [inline paper-server/src/main/java/io/papermc/paper/configuration/GlobalConfiguration.java]: Am I missing the migration, the old config is removed (well not really since you removed it from the wrong file per world config instead of global config) but not migrated to the new one?

Comment (kennytv) [reply paper-server/src/main/java/io/papermc/paper/configuration/GlobalConfiguration.java]: bad comment from when I had it done differently, the old option is ignored as behavior is different and all worlds are assumed to have had per-world time

File: paper-server/src/main/java/io/papermc/paper/configuration/RemovedConfigurations.java [hunk 10]
```diff
@@ -87,6 +87,7 @@ interface RemovedConfigurations {
         path("chunk-system", "gen-parallelism"),
         path("logging"), // server is no longer obfuscated since 26.1
         path("unsupported-settings", "compression-format"),
+        path("command", "time-command-affects-all-worlds") // replaced with time.affects-all-worlds
```
Comment (Lulu13022002) [inline paper-server/src/main/java/io/papermc/paper/configuration/RemovedConfigurations.java]: That's still not the right path: command**s**

File: paper-server/patches/sources/net/minecraft/world/clock/ServerClockManager.java.patch (hunk 5 above)
Comment (devspexx) [reply paper-server/patches/sources/net/minecraft/world/clock/ServerClockManager.java.patch:81]: XD
