### PR TITLE
Fix "DEFAULT" SpawnReason of fish spawned by bucket (#12225)

### LINKED ISSUE #12225: Spawn reason for fish spawn from bucket is default
### Expected behavior

The spawn reason for fish spawn from bucket should be "SPAWNER_EGG"

Image

This screen shot is from 1.16

### Observed/Actual behavior

The spawn reason for fish spawn from bucket is "DEFAULT"

Image

This screen shot is from 1.21

### Steps/models to reproduce

Listen for CreatureSpawningEvent and check spawn reason for fish in 1.16 and 1.21

    @EventHandler
    public void onFishSpawn(CreatureSpawnEvent event) {
        if (event.getEntity() instanceof org.bukkit.entity.Fish) {
            getLogger().info("A fish was spawned with reason: " + event.getSpawnReason() + " at " + event.getLocation());
        }
    }

### Plugin and Datapack List

Im only running my plugin to test spawn reason.

### Paper version

This server is running Paper version 1.21.4-188-main@8de7e35 (2025-03-03T16:59:40Z) (Implementing API version 1.21.4-R0.1-SNAPSHOT)

### Other

_No response_

### PR DESCRIPTION
**Pull request by renvins**
This PR fixes the problem described on #12225
Fixes #12225

Screen test

### CODE REVIEW

**Review by kennytv — APPROVED** [review]

File: paper-api/src/main/java/org/bukkit/event/entity/CreatureSpawnEvent.java [hunk 1]
```diff
@@ -211,6 +211,10 @@ public enum SpawnReason {
          * When an entity spawns from an ominous item spawner
          */
         OMINOUS_ITEM_SPAWNER,
+        /**
+         * When an entity spawns from a mob bucket
```
Comment (Warriorrrr) [inline paper-api/src/main/java/org/bukkit/event/entity/CreatureSpawnEvent.java]: I'd just call it a bucket here instead of mob bucket

Comment (renvins) [reply paper-api/src/main/java/org/bukkit/event/entity/CreatureSpawnEvent.java]: I'm going to modify it :)

**Comment by renvins** [comment]
@Warriorrrr done :)

**Review by Warriorrrr — APPROVED** [review]

**Review by electronicboy — APPROVED** [review]

**Review by NoahvdAa — APPROVED** [review]
