### PR TITLE
Fix save/load NaN Entity Motion

### LINKED ISSUE #12262: Server hangs when entity with NaN motion is loaded
### Stack trace

```
https://mclo.gs/G2OHmQA
```

### Plugin and Datapack List

None

### Actions to reproduce (if known)

_No response_

### Paper version

This server is running Paper version 1.21.4-207-main@1a7288a (2025-03-09T18:15:59Z) (Implementing API version 1.21.4-R0.1-SNAPSHOT)

### Other

A potion entity is loaded with NaN motion, causing failure when it's being ticked.
Position, yaw and pitch are guarded against NaN in `Entity.load`, but delta movement is not.

### PR DESCRIPTION
**Pull request by Doc94**
Fix #12262 using like the same logic than "pitch/yaw" for set to 0 when a value is NaN

### CODE REVIEW

**Comment by Doc94** [comment]
Note: currently this just fixs the save/load for the set this is ignored in teory the API avoid use that values but maybe can consider patch the Vec3 and just add the check in the constructor for set 0 when any value is NaN/Infinite

File: paper-server/patches/sources/net/minecraft/world/entity/Entity.java.patch [hunk 1]
```diff
@@ -758,6 +758,7 @@
 +             }
 +            // CraftBukkit end
  
++            this.setDeltaMovement(Double.isNaN(this.deltaMovement.x) ? 0 : this.deltaMovement.x, Double.isNaN(this.deltaMovement.y) ? 0 : this.deltaMovement.y, Double.isNaN(this.deltaMovement.z) ? 0 : this.deltaMovement.z); // Paper - remove NaN values before to be used in save
```
Comment (Warriorrrr) [inline paper-server/patches/sources/net/minecraft/world/entity/Entity.java.patch]:
```suggestion
+            this.setDeltaMovement(Double.isNaN(this.deltaMovement.x) ? 0 : this.deltaMovement.x, Double.isNaN(this.deltaMovement.y) ? 0 : this.deltaMovement.y, Double.isNaN(this.deltaMovement.z) ? 0 : this.deltaMovement.z); // Paper - remove NaN values before usage in saving
```

File: paper-server/patches/sources/net/minecraft/world/entity/Entity.java.patch [hunk 2]
```diff
@@ -854,6 +855,15 @@
              return compound;
          } catch (Throwable var9) {
              CrashReport crashReport = CrashReport.forThrowable(var9, "Saving entity NBT");
+@@ -1862,7 +_,7 @@
+             double _double1 = list1.getDouble(1);
+             double _double2 = list1.getDouble(2);
+             this.setDeltaMovement(
+-                Math.abs(_double) > 10.0 ? 0.0 : _double, Math.abs(_double1) > 10.0 ? 0.0 : _double1, Math.abs(_double2) > 10.0 ? 0.0 : _double2
++                Math.abs(_double) > 10.0 || Double.isNaN(_double) ? 0.0 : _double, Math.abs(_double1) > 10.0 || Double.isNaN(_double1) ? 0.0 : _double1, Math.abs(_double2) > 10.0 || Double.isNaN(_double2) ? 0.0 : _double2 // Paper - avoid set NaN values
```
Comment (Warriorrrr) [inline paper-server/patches/sources/net/minecraft/world/entity/Entity.java.patch]:
```suggestion
+                Math.abs(_double) > 10.0 || Double.isNaN(_double) ? 0.0 : _double, Math.abs(_double1) > 10.0 || Double.isNaN(_double1) ? 0.0 : _double1, Math.abs(_double2) > 10.0 || Double.isNaN(_double2) ? 0.0 : _double2 // Paper - avoid setting NaN values
```

**Review by Warriorrrr — COMMENTED** [review]
We could check isFinite if we want to also cover infinity, assuming that's even possible. Only have some nitpicks about the comments.

**Review by Owen1212055 — APPROVED** [review]

**Review by lynxplay — APPROVED** [review]
